'use strict';
// Category 1 — Battery & Amp-Hour Calculators
// Each tool ships a real pure `compute` function (also used by the test harness)
// and ~2000+ words of unique, entity-rich content.

const batteryRuntime = {
  slug: 'battery-runtime-calculator',
  category: 'Battery & Amp-Hour Calculators',
  kicker: 'Battery runtime planning',
  h1: 'Battery Runtime Calculator',
  title: 'Battery Runtime Calculator — How Long Will a Battery Last | Ampstowatt',
  metaDesc: 'Calculate how long a battery will last under load. Enter amp-hours, voltage, watt load, depth of discharge, and inverter efficiency for an accurate runtime in hours.',
  keywords: ['battery runtime calculator', 'how long will a battery last calculator', 'battery run time calculator', 'lithium battery runtime calculator', '12v battery run time calculator', 'deep cycle battery calculator'],
  formulaPill: 'Runtime (h) = Ah × V × DoD × η ÷ Load (W)',
  lead: 'Estimate <strong>how long a battery will last</strong> under a real watt load. This runtime calculator combines usable amp-hours, system voltage, depth of discharge, and inverter efficiency so you get a realistic number of hours — not the optimistic figure printed on the label.',
  reviewed: 'September 5, 2026',
  featureList: ['Battery runtime in hours and minutes', 'Depth-of-discharge and inverter-efficiency aware', 'Works for lithium (LiFePO4), AGM, gel, and flooded lead-acid', '12V, 24V, and 48V systems'],
  methodology: 'The calculator converts rated amp-hours into usable watt-hours (Ah × V × depth-of-discharge), applies inverter/system efficiency losses, then divides by the continuous watt load to return runtime. Depth of discharge defaults reflect chemistry norms: ~80–100% for LiFePO4 lithium and ~50% for lead-acid to protect cycle life.',
  calc: {
    id: 'battery-runtime',
    title: 'Battery Runtime Calculator',
    subtitle: 'How long a battery lasts under a watt load.',
    primaryLabel: 'Estimated Runtime',
    primaryUnit: 'hours',
    formulaText: 'Runtime = Ah × V × DoD × η ÷ Load',
    note: 'Usable energy after depth-of-discharge and inverter losses ÷ continuous load.',
    secondary: [
      { label: 'Usable Energy', unit: 'Wh' },
      { label: 'Runtime', unit: 'min' },
      { label: 'Rated Energy', unit: 'Wh' },
    ],
    inputs: [
      { id: 'capacity', label: 'Battery Capacity', unit: 'Ah', type: 'number', value: 100, min: 0 },
      { id: 'voltage', label: 'System Voltage', unit: 'V', type: 'select', value: '12', options: [{ v: '6', t: '6 V' }, { v: '12', t: '12 V' }, { v: '24', t: '24 V' }, { v: '36', t: '36 V' }, { v: '48', t: '48 V' }] },
      { id: 'load', label: 'Continuous Load', unit: 'W', type: 'number', value: 200, min: 0 },
      { id: 'dod', label: 'Usable Depth of Discharge', unit: '%', type: 'number', value: 80, min: 1, max: 100 },
      { id: 'eff', label: 'Inverter / System Efficiency', unit: '%', type: 'number', value: 90, min: 1, max: 100 },
    ],
    compute: function compute(v) {
      var usableWh = v.capacity * parseFloat(v.voltage) * (v.dod / 100) * (v.eff / 100);
      var hours = usableWh / v.load;
      var mins = hours * 60;
      return {
        primary: { label: 'Estimated Runtime', value: hours, unit: 'hours', precision: 2 },
        secondary: [
          { label: 'Usable Energy', value: usableWh, unit: 'Wh', precision: 0 },
          { label: 'Runtime', value: mins, unit: 'min', precision: 0 },
          { label: 'Rated Energy', value: v.capacity * parseFloat(v.voltage), unit: 'Wh', precision: 0 },
        ],
        formula: 'Runtime = ' + v.capacity + 'Ah × ' + v.voltage + 'V × ' + v.dod + '% × ' + v.eff + '% ÷ ' + v.load + 'W',
        note: 'Usable ' + Math.round(usableWh) + ' Wh ÷ ' + v.load + ' W load.',
      };
    },
    tests: [
      { name: '100Ah 12V 80% 90% @200W', in: { capacity: 100, voltage: '12', load: 200, dod: 80, eff: 90 }, expect: 4.32, tol: 0.01 },
      { name: '48V 200Ah 90% 92% @1000W', in: { capacity: 200, voltage: '48', load: 1000, dod: 90, eff: 92 }, expect: 7.9488, tol: 0.01 },
    ],
  },
  content: [
    { type: 'section', id: 'quick-answer', icon: '⚡', heading: 'How Long Will a Battery Last? Quick Answer', html: `<p class="content-p"><strong>To find battery runtime, convert amp-hours to usable watt-hours and divide by your load in watts.</strong> A 100Ah 12V lithium battery holds 1,200 watt-hours of rated energy. If you use 80% of it through a 90%-efficient inverter, roughly 864 usable watt-hours remain. Running a 200W load, that battery lasts about <strong>4.3 hours</strong>. The calculator above does this instantly and also shows usable watt-hours and runtime in minutes.</p><p class="content-p">The single most common mistake is dividing rated capacity by load and stopping there. Real-world runtime is always shorter because of two unavoidable factors: <strong>depth of discharge</strong> (you should not drain a battery to zero) and <strong>conversion efficiency</strong> (inverters, wiring, and heat waste energy). This tool builds both into the result so your estimate matches what you will actually see on a power meter.</p>` },
    { type: 'section', id: 'formula', icon: 'f(x)', heading: 'The Battery Runtime Formula Explained', html: `<p class="content-p">The runtime equation used by this calculator is:</p><div class="tool-guide-formula">Runtime (hours) = (Amp-hours × Voltage × Depth of Discharge × Efficiency) ÷ Load in Watts</div><p class="content-p">Each term matters:</p><ul><li><strong>Amp-hours (Ah)</strong> — the battery's charge capacity. A 100Ah battery can theoretically deliver 100 amps for one hour, or 5 amps for 20 hours.</li><li><strong>Voltage (V)</strong> — multiplying amp-hours by nominal voltage converts charge into <strong>energy</strong> (watt-hours). Energy is the currency of runtime because loads are rated in watts.</li><li><strong>Depth of Discharge (DoD)</strong> — the usable fraction of the battery. Lithium iron phosphate (LiFePO4) tolerates 80–100% DoD; flooded and AGM lead-acid last far longer if you stop near 50%.</li><li><strong>Efficiency (η)</strong> — inverter conversion, Peukert losses, wiring resistance, and temperature. 85–95% is typical for a good pure sine-wave inverter running a moderate load.</li></ul><p class="content-p">Because watt-hours (energy) and watts (power) share the same base unit, dividing energy by power yields time. This is the same relationship behind <a href="/amp-hours-to-watt-hours/">amp-hours to watt-hours</a> and <a href="/watt-hours-to-amp-hours-calculator/">watt-hours to amp-hours</a> conversions.</p>`, table: { caption: 'Usable capacity by battery chemistry (recommended depth of discharge)', columns: ['Battery Type', 'Recommended DoD', 'Cycle-Life Impact', 'Best Use'], rows: [['LiFePO4 (Lithium)', '80–100%', 'Minimal at 80%', 'Solar, RV, marine, off-grid'], ['Li-ion (NMC)', '80–90%', 'Low', 'Portable power stations'], ['AGM Lead-Acid', '50%', 'High below 50%', 'Backup, occasional cycling'], ['Gel Lead-Acid', '50%', 'High below 50%', 'Deep-cycle backup'], ['Flooded Lead-Acid', '50%', 'Very high below 50%', 'Golf carts, off-grid budget banks']] } },
    { type: 'section', id: 'examples', icon: '#', heading: 'Worked Examples: Real Battery Runtime Scenarios', html: `<p class="content-p">These worked examples show how depth of discharge and voltage change the answer for the same nominal capacity.</p><p class="content-p"><strong>Example 1 — 12V 100Ah lithium running a mini-fridge:</strong> A 60W fridge draws power intermittently, but assume 60W continuous for a conservative estimate. Usable energy = 100 × 12 × 0.90 × 0.90 = 972 Wh. Runtime = 972 ÷ 60 = <strong>16.2 hours</strong>. Because fridges cycle on and off, real runtime is often 1.5–2× longer.</p><p class="content-p"><strong>Example 2 — 12V 100Ah AGM running a 500W load:</strong> Lead-acid should stop at 50% DoD. Usable energy = 100 × 12 × 0.50 × 0.85 = 510 Wh. Runtime = 510 ÷ 500 = <strong>1.0 hour</strong>. The same physical battery in lithium (80% DoD, 90% efficiency) would give 100 × 12 × 0.80 × 0.90 ÷ 500 = 1.73 hours — a 70% gain purely from chemistry.</p><p class="content-p"><strong>Example 3 — 48V 200Ah off-grid bank powering a 1,000W home load:</strong> Usable energy = 200 × 48 × 0.90 × 0.92 = 7,948 Wh. Runtime = 7,948 ÷ 1,000 = <strong>7.9 hours</strong>. Higher system voltage reduces current, which cuts wiring losses and lets you use thinner cable — a key reason larger off-grid and solar systems move to 48V.</p><p class="content-p"><strong>Example 4 — 12V 20Ah battery for a CPAP machine:</strong> Usable = 20 × 12 × 0.80 × 0.85 = 163 Wh. A CPAP without a humidifier draws ~30W, giving 163 ÷ 30 = <strong>5.4 hours</strong> — short of a full night, which is why campers size 30–50Ah for CPAP use.</p>` },
    { type: 'section', id: 'chemistry', icon: '🔋', heading: 'Lithium vs Lead-Acid: Why Chemistry Doubles Runtime', html: `<p class="content-p">Two 100Ah batteries are not equal. A LiFePO4 lithium battery delivers roughly <strong>double the usable runtime</strong> of a lead-acid battery of the same rated capacity, for three reasons:</p><ol><li><strong>Deeper discharge.</strong> Lithium safely uses 80–100% of capacity; lead-acid should stop at 50% to avoid rapid cycle-life loss.</li><li><strong>Flatter voltage curve.</strong> Lithium holds voltage near nominal until nearly empty, so inverters run efficiently the whole way down. Lead-acid voltage sags under load, tripping low-voltage cutoffs early.</li><li><strong>Peukert effect.</strong> Lead-acid capacity <em>shrinks</em> at high discharge rates (the Peukert exponent), while lithium is largely immune. A lead-acid battery rated at a 20-hour rate delivers noticeably fewer amp-hours when discharged in two hours.</li></ol><p class="content-p">This is why an off-grid, RV, or marine system sized in lithium can use a smaller, lighter bank for the same runtime. When comparing quotes, always compare <strong>usable watt-hours</strong>, not nameplate amp-hours. Pair this tool with the <a href="/battery-bank-size-calculator/">battery bank size calculator</a> to size a bank for a target number of days of autonomy.</p>` },
    { type: 'section', id: 'how-to-use', icon: '✓', heading: 'How to Use the Battery Runtime Calculator', html: `<ol><li><strong>Enter battery capacity in amp-hours (Ah).</strong> Find it on the battery label or spec sheet. For multiple batteries in parallel, add their amp-hours together.</li><li><strong>Select system voltage.</strong> Use the nominal bank voltage (12V, 24V, or 48V), not the fully-charged voltage. Batteries in series add voltage; batteries in parallel add amp-hours.</li><li><strong>Enter your continuous load in watts.</strong> Add up every device that runs at once. If you only know amps, multiply amps × voltage, or use the <a href="/ac-amps-to-watts-calculator/">amps to watts calculator</a>.</li><li><strong>Set depth of discharge.</strong> Use 80–100% for lithium, 50% for lead-acid. This protects the battery and gives an honest runtime.</li><li><strong>Set inverter/system efficiency.</strong> Use 90% for a quality pure sine-wave inverter, 85% for modified sine or heavily loaded systems, or 100% for DC-direct loads with no inverter.</li></ol><p class="content-p">The result updates live. Copy it, or adjust the load to see how much longer a smaller draw would last — a fast way to plan which appliances to run during an outage.</p>` },
    { type: 'section', id: 'applications', icon: '⌂', heading: 'Sizing Runtime for RV, Marine, Solar, and Backup', html: `<p class="content-p">Runtime targets differ by application, and knowing the target helps you decide how many amp-hours to buy.</p><p class="content-p"><strong>RV and van life.</strong> Boondockers typically size for a full evening plus overnight — lights, a 12V fridge, water pump, fans, and device charging. A 100–200Ah lithium bank paired with 200–400W of solar is a common baseline. Enter your realistic combined load; a 12V fridge alone averages 30–60W over a day.</p><p class="content-p"><strong>Marine.</strong> Boats add navigation electronics, bilge pumps, and refrigeration that must survive overnight anchorages. Because charging opportunities are limited, marine banks are often oversized and lithium is popular for weight and deep-cycle durability.</p><p class="content-p"><strong>Off-grid solar homes.</strong> Here runtime becomes "days of autonomy" — how long the bank carries the house with no sun. This is best handled with the <a href="/battery-bank-size-calculator/">battery bank size calculator</a> and <a href="/off-grid-solar-calculator/">off-grid solar calculator</a>, which layer daily consumption and autonomy on top of the single-load runtime math here.</p><p class="content-p"><strong>Home backup during outages.</strong> Prioritize essentials: fridge, a few lights, internet, and phone charging usually total 150–300W averaged. A 100Ah lithium battery can carry those essentials for most of a day; larger banks or a paired inverter/charger extend that indefinitely when combined with solar or a generator.</p>` },
    { type: 'section', id: 'runtime-table', icon: '⏱', heading: 'Battery Runtime Reference Table by Load', html: `<p class="content-p">The table below shows approximate runtime for a single 12V battery at common loads, using realistic usable-energy assumptions (lithium at 80% DoD / 90% efficiency ≈ 864 usable Wh per 100Ah; lead-acid at 50% DoD / 85% efficiency ≈ 510 usable Wh per 100Ah). Use it as a fast sanity check against the live calculator.</p><p class="content-p">Notice how a 100Ah lithium battery outlasts a 100Ah lead-acid battery at every load — the runtime gap widens as the load grows, because lead-acid also suffers Peukert capacity loss at higher discharge rates. For sustained high-watt loads, lithium and higher system voltage are almost always the more cost-effective path once you account for usable energy and cycle life.</p>`, table: { caption: 'Approximate runtime for a 12V 100Ah battery (hours)', columns: ['Continuous Load', 'Lithium (LiFePO4)', 'AGM Lead-Acid', 'Typical Devices'], rows: [['25 W', '34.6 h', '20.4 h', 'LED lights, phone charging, router'], ['50 W', '17.3 h', '10.2 h', 'Laptop, small fan, CPAP'], ['100 W', '8.6 h', '5.1 h', 'TV, mini-fridge (continuous)'], ['200 W', '4.3 h', '2.6 h', 'Full-size fridge cycling, tools'], ['500 W', '1.7 h', '1.0 h', 'Microwave, coffee maker, power tools'], ['1000 W', '0.86 h', '0.51 h', 'Space heater, kettle, induction burner']] } },
    { type: 'section', id: 'temperature', icon: '°', heading: 'Temperature, Age, and the Peukert Effect', html: `<p class="content-p">Three real-world factors quietly reduce runtime below the ideal calculation, and understanding them helps you set the efficiency input honestly.</p><p class="content-p"><strong>Temperature.</strong> Battery capacity is rated at about 25°C (77°F). Lead-acid can lose 20–35% of usable capacity near freezing, and even lithium loses some capacity in the cold (and should not be charged below 0°C without a heater). In hot climates, high temperatures accelerate aging and self-discharge. If you operate in the cold, drop the efficiency input by 10–20% to stay realistic.</p><p class="content-p"><strong>Age and cycle count.</strong> A battery gradually loses capacity as it cycles. Lead-acid may retain 80% capacity after 300–500 cycles; quality LiFePO4 can deliver 3,000–6,000 cycles to 80%. A three-year-old "100Ah" battery may effectively be an 85Ah battery — enter its real measured capacity for an accurate result.</p><p class="content-p"><strong>The Peukert effect.</strong> Lead-acid batteries deliver fewer amp-hours when discharged quickly. A battery rated 100Ah at a 20-hour rate might yield only 75–80Ah when drained in 2 hours. Lithium is largely immune, which is another reason its real-world runtime beats lead-acid at high loads. This is why manufacturers quote capacity at a specific discharge rate (C/20, C/10, C/5).</p>` },
    { type: 'section', id: 'series-parallel', icon: '⇄', heading: 'Series vs Parallel: How Wiring Changes Capacity', html: `<p class="content-p">How you wire multiple batteries determines whether you gain <strong>voltage</strong> or <strong>amp-hours</strong>, and it directly affects the numbers you enter above.</p><ul><li><strong>Series wiring</strong> (positive to negative) adds voltage while amp-hours stay the same. Two 12V 100Ah batteries in series make a 24V 100Ah bank (still 2,400 Wh).</li><li><strong>Parallel wiring</strong> (positive to positive) adds amp-hours while voltage stays the same. Two 12V 100Ah batteries in parallel make a 12V 200Ah bank (also 2,400 Wh).</li><li><strong>Series-parallel</strong> combines both for larger banks — e.g., four 12V 100Ah batteries as 24V 200Ah (4,800 Wh).</li></ul><p class="content-p">Total stored energy in watt-hours is identical for series and parallel of the same batteries; only voltage and current change. Higher voltage banks (24V, 48V) draw less current for the same power, reducing wire size, breaker rating, and resistive losses — which is why whole-home and large solar systems favor 48V. To convert a bank's amp-hours into energy either way, use the <a href="/amp-hours-to-watt-hours/">Ah to Wh calculator</a>.</p>` },
    { type: 'section', id: 'mistakes', icon: '!', heading: 'Common Mistakes That Wreck Runtime Estimates', html: `<ul><li><strong>Using rated capacity instead of usable capacity.</strong> The label number assumes a full 100% discharge that most chemistries cannot sustain.</li><li><strong>Ignoring inverter losses.</strong> Converting 12V DC to 120V AC costs 5–15% before the load sees a single watt.</li><li><strong>Forgetting surge loads.</strong> Motors, compressors, and pumps draw 3–7× their running watts at startup. Size the inverter for surge, but calculate runtime on running watts.</li><li><strong>Mixing old and new batteries.</strong> A weak cell drags down a parallel bank; the whole bank behaves like its worst battery.</li><li><strong>Discharging lead-acid below 50% routinely.</strong> It can cut cycle life from 500 cycles to under 200.</li></ul><p class="content-p">For load planning across a whole system, combine this with the <a href="/power-consumption-calculator/">power consumption calculator</a> and the <a href="/inverter-size-calculator/">inverter size calculator</a>.</p>` },
  ],
  faq: [
    { q: 'How do I calculate how long my battery will last?', a: 'Convert amp-hours to watt-hours (Ah × voltage), multiply by your usable depth of discharge and inverter efficiency, then divide by your load in watts. Example: a 100Ah 12V lithium battery at 80% DoD and 90% efficiency has 864 usable watt-hours; running a 100W load it lasts about 8.6 hours.' },
    { q: 'How long will a 100Ah battery last?', a: 'It depends on the load. A 100Ah 12V battery holds 1,200 rated watt-hours (about 864 usable for lithium). At a 50W load that is roughly 17 hours; at 200W about 4.3 hours; at 500W about 1.7 hours. Lead-acid versions last roughly half as long because they should only discharge to 50%.' },
    { q: 'Why does my battery die faster than the calculator says?', a: 'Common causes are high-surge appliances, cold temperatures (which reduce lead-acid capacity), an aging battery that no longer holds its rated amp-hours, an inefficient modified sine-wave inverter, or additional phantom loads you did not include. Lower the efficiency input to 80–85% for a more conservative estimate.' },
    { q: 'What depth of discharge should I use for lithium vs lead-acid?', a: 'Use 80–100% for LiFePO4 lithium and 50% for AGM, gel, or flooded lead-acid. Discharging lead-acid deeper than 50% dramatically shortens its cycle life, while lithium is designed for deep, repeated discharge.' },
    { q: 'Does higher voltage make a battery last longer?', a: 'Not for the same watt-hours — a 12V 100Ah and a 24V 50Ah battery store the same 1,200 Wh and last the same time on a given watt load. Higher voltage helps by reducing current, which lowers wiring and inverter losses, so real-world efficiency (and effective runtime) improves slightly.' },
    { q: 'How do I extend battery runtime?', a: 'Reduce continuous load, switch to lithium for deeper usable discharge, add batteries in parallel to increase amp-hours, use a more efficient inverter (or run DC loads directly), keep batteries warm, and avoid high-surge appliances. Doubling amp-hours doubles runtime; halving the load also doubles it.' },
  ],
  related: [
    { href: '/battery-bank-size-calculator/', badge: 'Ah', title: 'Battery Bank Size Calculator', desc: 'Size a bank for days of autonomy' },
    { href: '/amp-hours-to-watt-hours/', badge: 'Wh', title: 'Amp Hours to Watt Hours', desc: 'Convert Ah into energy' },
    { href: '/watt-hours-to-amp-hours-calculator/', badge: 'Ah', title: 'Watt Hours to Amp Hours', desc: 'Reverse energy conversion' },
    { href: '/inverter-size-calculator/', badge: 'INV', title: 'Inverter Size Calculator', desc: 'Match inverter to your loads' },
    { href: '/solar-battery-bank-calculator/', badge: '☀', title: 'Solar Battery Bank Calculator', desc: 'Off-grid storage sizing' },
    { href: '/power-consumption-calculator/', badge: 'kWh', title: 'Power Consumption Calculator', desc: 'Estimate device energy use' },
  ],
};

module.exports = [batteryRuntime];
