'use strict';
// Category 5 — EV & Charging Calculators
// Each tool ships a pure `compute` function (also used by the test harness)
// and 2000+ words of unique, entity-rich content.

const evChargingTime = {
  slug: 'ev-charging-time-calculator',
  category: 'EV & Charging Calculators',
  kicker: 'EV charging time planning',
  h1: 'EV Charging Time Calculator',
  title: 'EV Charging Time Calculator — How Long to Charge an EV | Ampstowatt',
  metaDesc: 'Calculate how long it takes to charge an electric car. Enter battery size, charger power, start and end state of charge, and efficiency for an accurate charge time in hours.',
  keywords: ['ev charging time calculator', 'how long to charge ev calculator', 'electric car charging time', 'ev charge time calculator', 'how long to charge electric car', 'tesla charging time calculator'],
  formulaPill: 'Time (h) = kWh added ÷ (Charger kW × η)',
  lead: 'Estimate <strong>how long it takes to charge an EV</strong> from any starting state of charge to any target. This EV charging time calculator combines battery capacity, charger power, and charging efficiency so the number of hours you see matches what actually shows on the dashboard, not the theoretical best case.',
  reviewed: 'September 5, 2026',
  featureList: ['Charge time in hours and minutes', 'Works for Level 1, Level 2, and DC fast charging', 'State-of-charge aware (20% to 80%, etc.)', 'Charging-efficiency corrected'],
  methodology: 'The calculator finds the energy that must move into the pack — battery capacity times the change in state of charge — then divides by the effective charging power, which is the charger rating multiplied by charging efficiency. Charging efficiency accounts for AC-to-DC conversion, thermal management, and onboard-charger losses, typically 85–92% for Level 2 AC charging.',
  calc: {
    id: 'ev-charging-time',
    title: 'EV Charging Time Calculator',
    subtitle: 'How long to charge an electric car between two states of charge.',
    primaryLabel: 'Charging Time',
    primaryUnit: 'hours',
    formulaText: 'Time = (kWh × ΔSOC) ÷ (Charger kW × efficiency)',
    note: 'Energy added to the pack divided by effective charging power.',
    secondary: [
      { label: 'Energy Added', unit: 'kWh' },
      { label: 'Charging Time', unit: 'min' },
      { label: 'Effective Power', unit: 'kW' },
    ],
    inputs: [
      { id: 'battery', label: 'Battery Capacity', unit: 'kWh', type: 'number', value: 60, min: 0 },
      { id: 'power', label: 'Charger Power', unit: 'kW', type: 'number', value: 7.4, min: 0, step: 0.1 },
      { id: 'start', label: 'Start State of Charge', unit: '%', type: 'number', value: 20, min: 0, max: 100 },
      { id: 'end', label: 'End State of Charge', unit: '%', type: 'number', value: 80, min: 0, max: 100 },
      { id: 'eff', label: 'Charging Efficiency', unit: '%', type: 'number', value: 90, min: 1, max: 100 },
    ],
    compute: function compute(v) {
      var kWhAdded = v.battery * (v.end - v.start) / 100;
      var effPower = v.power * (v.eff / 100);
      var hours = kWhAdded / effPower;
      return {
        primary: { label: 'Charging Time', value: hours, unit: 'hours', precision: 2 },
        secondary: [
          { label: 'Energy Added', value: kWhAdded, unit: 'kWh', precision: 2 },
          { label: 'Charging Time', value: hours * 60, unit: 'min', precision: 0 },
          { label: 'Effective Power', value: effPower, unit: 'kW', precision: 2 },
        ],
        formula: 'Time = (' + v.battery + ' × ' + (v.end - v.start) + '%) ÷ (' + v.power + ' × ' + v.eff + '%)',
        note: kWhAdded.toFixed(1) + ' kWh added at ' + effPower.toFixed(1) + ' kW effective.',
      };
    },
    tests: [
      { name: '60kWh 20-80 @7.4kW 90%', in: { battery: 60, power: 7.4, start: 20, end: 80, eff: 90 }, expect: 5.4054, tol: 0.01 },
      { name: '75kWh 10-100 @11kW 90%', in: { battery: 75, power: 11, start: 10, end: 100, eff: 90 }, expect: 6.8182, tol: 0.01 },
    ],
  },
  content: [
    { type: 'section', id: 'quick-answer', icon: '⚡', heading: 'How Long Does It Take to Charge an EV? Quick Answer', html: `<p class="content-p"><strong>To find EV charging time, work out how many kilowatt-hours you need to add, then divide by the effective charging power.</strong> A 60 kWh battery charging from 20% to 80% needs to absorb 36 kWh (60 × 0.60). On a 7.4 kW Level 2 charger at 90% efficiency the pack effectively receives about 6.66 kW, so the charge takes roughly <strong>5.4 hours</strong>. The calculator above returns this instantly along with the energy added and the time in minutes.</p><p class="content-p">The most common mistake is dividing the whole battery size by the charger rating and stopping there. Real charge time depends on the <strong>state-of-charge window</strong> you actually drive through — most people top up from 20–30% to 80%, not from empty to full — and on <strong>charging losses</strong> that mean not every watt from the wall reaches the cells. Building both into the number gives you a plan you can trust for an overnight charge or a road-trip stop.</p>` },
    { type: 'section', id: 'formula', icon: 'f(x)', heading: 'The EV Charging Time Formula Explained', html: `<p class="content-p">The equation used by this calculator is:</p><div class="tool-guide-formula">Charging Time (hours) = (Battery kWh × (End SOC − Start SOC) ÷ 100) ÷ (Charger kW × Efficiency)</div><p class="content-p">Each term controls the result:</p><ul><li><strong>Battery kWh</strong> — usable pack capacity. A car marketed as "64 kWh" often has a usable figure a little lower; use the usable number when you know it.</li><li><strong>State of charge (SOC)</strong> — the percentage window you are filling. Charging 20→80% moves 60% of the pack; 10→100% moves 90%. Battery preconditioning and the automaker's charge limit both live here.</li><li><strong>Charger kW</strong> — the real delivered power, which is the lower of the charger's output and the car's onboard AC charger. A 7.4 kW wallbox feeding a car with a 7.2 kW onboard charger delivers 7.2 kW.</li><li><strong>Efficiency (η)</strong> — AC-to-DC conversion in the onboard charger, plus battery thermal management. Level 2 AC charging is roughly 85–92% efficient; DC fast charging bypasses the onboard charger and is efficient at the pack but tapers hard near the top.</li></ul><p class="content-p">Because a kilowatt-hour of energy divided by a kilowatt of power yields hours, the units resolve cleanly to time. To turn that time into a dollar figure, pair this with the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a>, and to size the circuit and breaker your charger needs, use the <a href="/home-ev-charger-amp-calculator/">home EV charger amp calculator</a>.</p>`, table: { caption: 'Typical charging power by level and hardware', columns: ['Charging Level', 'Typical Power', 'Source', 'Range Added per Hour*'], rows: [['Level 1 (120 V)', '1.4–1.9 kW', 'Standard household outlet', '3–5 miles'], ['Level 2 (240 V) home', '7.2–11.5 kW', '32–48 A wallbox', '25–40 miles'], ['Level 2 (240 V) public', '7–19.2 kW', 'Commercial AC station', '25–65 miles'], ['DC Fast (Level 3)', '50–350 kW', 'Public DC charger', '150–1000+ miles'], ['Tesla Supercharger V3', 'up to 250 kW', 'Tesla network', '200+ miles at peak']] } },
    { type: 'section', id: 'examples', icon: '#', heading: 'Worked Examples: Real EV Charging Scenarios', html: `<p class="content-p">These examples show how the SOC window and charger choice reshape the same battery's charge time.</p><p class="content-p"><strong>Example 1 — 60 kWh crossover, 20→80% on a home Level 2 charger:</strong> Energy added = 60 × 0.60 = 36 kWh. Effective power at 7.4 kW and 90% efficiency = 6.66 kW. Time = 36 ÷ 6.66 = <strong>5.4 hours</strong> — a comfortable overnight charge that leaves a healthy 80% buffer for battery longevity.</p><p class="content-p"><strong>Example 2 — 75 kWh sedan, 10→100% on an 11 kW charger:</strong> Energy added = 75 × 0.90 = 67.5 kWh. Effective power = 11 × 0.90 = 9.9 kW. Time = 67.5 ÷ 9.9 = <strong>6.8 hours</strong>. Filling the last 20% takes disproportionately long in the real world because AC charging holds steady but many owners reserve 100% only for trips.</p><p class="content-p"><strong>Example 3 — 82 kWh SUV, 30→80% on Level 1 (120 V) overnight:</strong> Energy added = 82 × 0.50 = 41 kWh. Effective power at 1.4 kW and 85% efficiency = 1.19 kW. Time = 41 ÷ 1.19 = <strong>34.5 hours</strong>. This is why Level 1 is a trickle: fine for a plug-in hybrid or a low-mileage commuter, impractical for a big battery.</p><p class="content-p"><strong>Example 4 — DC fast charge, 60 kWh, 20→80% at an average 60 kW:</strong> Energy added = 36 kWh. At 60 kW average delivered power (fast chargers taper, so the peak is higher), time ≈ 36 ÷ 60 = 0.6 hours, about <strong>36 minutes</strong>. DC charging skips the onboard AC charger, so we treat efficiency as near the pack; the taper above 80% is why fast-charge sessions usually stop at 80%.</p>` },
    { type: 'section', id: 'why-2080', icon: '↕', heading: 'Why 20% to 80% Is the Charging Sweet Spot', html: `<p class="content-p">Almost every EV maker and battery engineer recommends daily charging in a <strong>20–80% window</strong>, and it changes the time math in a useful way. Lithium-ion cells age fastest when held at very high or very low state of charge, so avoiding the top and bottom of the pack extends calendar and cycle life. It also happens to be the fastest, most efficient region of the charge curve on DC.</p><p class="content-p">On DC fast charging the difference is dramatic. Charging 20→80% might take 30–40 minutes, but pushing on from 80→100% can take almost as long again because the current tapers sharply to protect the cells. That is why road-trip planning is built around 10–80% legs, not full charges. On AC Level 2 the taper is far gentler, so filling to 100% occasionally for a long trip is fine.</p><p class="content-p">The practical takeaway: set your car's charge limit to 80% for daily use and only schedule 100% right before departure. Use this calculator with your typical window — most owners find a nightly 30→80% top-up on a Level 2 charger takes only 2–4 hours, easily covered by an overnight or off-peak schedule. To see what that costs on a time-of-use plan, run the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a>.</p>` },
    { type: 'section', id: 'how-to-use', icon: '✓', heading: 'How to Use the EV Charging Time Calculator', html: `<ol><li><strong>Enter battery capacity in kWh.</strong> Use the usable capacity from your spec sheet if available; the marketed "gross" figure will slightly overstate charge time.</li><li><strong>Enter charger power in kW.</strong> Use the lower of your wallbox output and the car's onboard AC charger. Common values are 1.4 kW (Level 1), 7.4–11.5 kW (home Level 2), or the average delivered kW for a DC session.</li><li><strong>Set the start and end state of charge.</strong> These are the percentages shown on the dashboard. A 20→80% window is the practical default for daily charging.</li><li><strong>Set charging efficiency.</strong> Use 90% for typical Level 2 AC charging, 85% for cold-weather or heavily loaded conditions, or 95%+ for DC fast charging measured at the pack.</li></ol><p class="content-p">The result updates live in hours and minutes. Adjust the charger power to compare a 7.4 kW versus 11.5 kW wallbox, or change the SOC window to see how much time the final 20% really costs. If you are still choosing hardware, the <a href="/home-ev-charger-amp-calculator/">home EV charger amp calculator</a> shows the amps and breaker each option requires, and the <a href="/ev-range-calculator/">EV range calculator</a> estimates the miles each charge delivers.</p>` },
    { type: 'section', id: 'factors', icon: '⚙', heading: 'What Slows Real EV Charging Down', html: `<p class="content-p">The formula gives a clean number, but several real-world factors push actual charge time longer, especially on fast chargers.</p><p class="content-p"><strong>Onboard charger limit.</strong> A car's AC charging speed is capped by its onboard charger, not the wallbox. Plug a 7.2 kW car into an 11.5 kW charger and it still charges at 7.2 kW. Always use the lower of the two figures.</p><p class="content-p"><strong>Temperature and preconditioning.</strong> Cold packs charge slowly because the battery management system limits current to protect the cells. Many EVs precondition the battery when navigating to a fast charger, warming it for peak speed. In freezing weather without preconditioning, DC charge times can double.</p><p class="content-p"><strong>The charge curve and taper.</strong> DC fast charging is fastest at low state of charge and tapers as the pack fills. A car that peaks at 150 kW at 20% may be down to 50 kW by 80%. That is why we use an <em>average</em> delivered kW for DC estimates rather than the headline peak.</p><p class="content-p"><strong>Shared and derated stations.</strong> Two cars sharing a fast-charge cabinet can each get half power. Hot ambient temperatures also make some stations derate to protect their own electronics. For home AC charging none of this applies — the steady, predictable power is exactly why overnight charging is the backbone of EV ownership.</p>` },
    { type: 'section', id: 'level-table', icon: '⏱', heading: 'Charging Time Reference Table by Charger and Battery', html: `<p class="content-p">The table below shows approximate 20→80% charge times (moving 60% of the pack) at three common power levels, using 90% efficiency for AC and average delivered power for DC. Use it as a sanity check against the live calculator.</p><p class="content-p">Notice how doubling the charger power roughly halves the time on AC, while DC fast charging compresses hours into minutes. The gap is why most owners install a Level 2 charger at home for daily overnight charging and rely on DC fast charging only for road trips.</p>`, table: { caption: 'Approximate 20→80% charge time (hours:minutes)', columns: ['Battery Size', 'Level 1 (1.4 kW)', 'Level 2 (7.4 kW)', 'Level 2 (11.5 kW)', 'DC (60 kW avg)'], rows: [['40 kWh', '19:03', '3:36', '2:19', '0:24'], ['60 kWh', '28:34', '5:24', '3:29', '0:36'], ['77 kWh', '36:40', '6:56', '4:28', '0:46'], ['100 kWh', '47:37', '9:00', '5:48', '1:00']] } },
    { type: 'section', id: 'home-vs-public', icon: '⌂', heading: 'Home Overnight vs Public Fast Charging Strategy', html: `<p class="content-p">The smartest charging strategy uses the two systems for what each does best, and the time math makes the case.</p><p class="content-p"><strong>Home Level 2 for daily driving.</strong> Most drivers cover 30–40 miles a day, which a 7.4–11.5 kW home charger replaces in one to two hours overnight — well within an off-peak window. Because the car sits parked anyway, slow steady charging is free time and is gentle on the battery. Size the circuit with the <a href="/home-ev-charger-amp-calculator/">home EV charger amp calculator</a>, then estimate the running cost with the <a href="/electricity-cost-calculator/">electricity cost calculator</a>.</p><p class="content-p"><strong>DC fast charging for trips.</strong> On the road, minutes matter and battery aging over a few sessions does not. Planning 10–80% legs keeps each stop near the fast part of the charge curve, typically 20–40 minutes. Beyond 80%, the taper makes it faster to drive on and stop again than to wait for a full charge.</p><p class="content-p"><strong>Level 1 as a backstop.</strong> A standard 120 V outlet adds only 3–5 miles per hour, but for a plug-in hybrid or a very low-mileage EV it can be enough, and it needs no installation. Enter 1.4 kW above to see whether a trickle charge keeps up with your daily miles.</p>` },
    { type: 'section', id: 'mistakes', icon: '!', heading: 'Common Mistakes in Charging Time Estimates', html: `<ul><li><strong>Using the charger rating instead of the car's onboard limit.</strong> AC speed is capped by the slower of the two — a common reason a new wallbox feels no faster.</li><li><strong>Charging from empty to full in your estimate.</strong> Daily charging almost never uses the whole pack; a 20→80% window is both realistic and faster.</li><li><strong>Ignoring efficiency losses.</strong> 8–15% of the energy from the wall never reaches the cells on AC; leaving it out understates both time and cost.</li><li><strong>Expecting peak DC speed the whole session.</strong> Fast charging tapers; use an average delivered kW, not the headline number.</li><li><strong>Forgetting cold-weather derating.</strong> A cold pack charges slowly until preconditioned — plan extra time in winter.</li></ul><p class="content-p">For a full picture of a charge session, combine this tool with the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a> and the <a href="/battery-charge-time-calculator/">battery charge time calculator</a> for 12 V and auxiliary batteries.</p>` },
  ],
  faq: [
    { q: 'How long does it take to charge an electric car?', a: 'It depends on battery size, charger power, and the state-of-charge window. A 60 kWh EV charging 20→80% on a 7.4 kW Level 2 charger takes about 5.4 hours; on an 11.5 kW charger about 3.5 hours; on a DC fast charger averaging 60 kW about 36 minutes. Level 1 (120 V) can take a full day or more for a large pack.' },
    { q: 'How long to charge an EV from 20% to 80%?', a: 'Charging 20→80% moves 60% of the battery. For a 60 kWh pack that is 36 kWh. At 7.4 kW and 90% efficiency it takes about 5.4 hours; at 11.5 kW about 3.5 hours; at a 60 kW DC average about 36 minutes. The 20–80% window is recommended because it charges fastest on DC and is gentlest on battery life.' },
    { q: 'Why is my EV charging slower than the calculator says?', a: 'The most common cause is the car\'s onboard AC charger being slower than the wallbox — AC speed is capped by the lower of the two. Cold temperatures, a battery that has not preconditioned, a shared or derated public station, and the DC taper above 80% also slow real charging. Lower the efficiency input or use the average delivered kW for a more realistic estimate.' },
    { q: 'Does charging to 100% take longer per percent?', a: 'On DC fast charging, yes — the current tapers sharply above 80% to protect the cells, so the last 20% can take almost as long as the first 60%. On AC Level 2 charging the power stays roughly constant, so each percent takes about the same time. This is why road trips are planned around 10–80% legs.' },
    { q: 'What charging efficiency should I use?', a: 'Use about 90% for typical Level 2 AC charging, 85% for cold weather or heavily loaded conditions, and 95% or higher for DC fast charging measured at the pack. The losses come from AC-to-DC conversion in the onboard charger and battery thermal management, so DC charging (which bypasses the onboard charger) is more efficient at the battery.' },
    { q: 'How much faster is an 11.5 kW charger than a 7.4 kW charger?', a: 'Roughly 55% faster on AC, if the car can accept the full power. A 60 kWh 20→80% charge takes about 5.4 hours at 7.4 kW versus about 3.5 hours at 11.5 kW. The gain only materializes if the car\'s onboard charger supports 11.5 kW; many EVs cap at 7.2–7.7 kW, in which case the faster wallbox makes no difference.' },
    { q: 'Can I charge an EV overnight on a normal outlet?', a: 'You can, but a standard 120 V Level 1 outlet only delivers about 1.4 kW, adding 3–5 miles of range per hour. Over an 8-hour night that is roughly 25–40 miles — enough for a short commuter or a plug-in hybrid, but not enough to refill a large battery. Most EV owners install a 240 V Level 2 charger for practical daily charging.' },
  ],
  related: [
    { href: '/ev-charging-cost-calculator/', badge: '$', title: 'EV Charging Cost Calculator', desc: 'Cost to charge your EV per session' },
    { href: '/home-ev-charger-amp-calculator/', badge: 'A', title: 'Home EV Charger Amp Calculator', desc: 'Size the circuit and breaker' },
    { href: '/ev-range-calculator/', badge: 'mi', title: 'EV Range Calculator', desc: 'Miles from a full charge' },
    { href: '/battery-charge-time-calculator/', badge: 'Ah', title: 'Battery Charge Time Calculator', desc: 'Charge time for 12 V batteries' },
    { href: '/electricity-cost-calculator/', badge: 'kWh', title: 'Electricity Cost Calculator', desc: 'Cost of energy per kWh' },
    { href: '/battery-runtime-calculator/', badge: 'h', title: 'Battery Runtime Calculator', desc: 'How long a battery lasts' },
  ],
};

const evChargingCost = {
  slug: 'ev-charging-cost-calculator',
  category: 'EV & Charging Calculators',
  kicker: 'EV charging cost planning',
  h1: 'EV Charging Cost Calculator',
  title: 'EV Charging Cost Calculator — Cost to Charge an Electric Car | Ampstowatt',
  metaDesc: 'Calculate the cost to charge an electric car. Enter battery size, state of charge, electricity rate, and charging efficiency to see the dollar cost per session and per full charge.',
  keywords: ['ev charging cost calculator', 'tesla charging cost calculator', 'cost to charge ev', 'electric car charging cost', 'how much to charge an ev', 'ev charging cost per kwh'],
  formulaPill: 'Cost = (kWh added ÷ η) × Rate',
  lead: 'Find the <strong>cost to charge an EV</strong> for any charging session. This EV charging cost calculator turns your battery size, state-of-charge window, electricity rate, and charging efficiency into a dollar figure — including the grid energy you pay for but lose to charging inefficiency.',
  reviewed: 'September 5, 2026',
  featureList: ['Cost per charging session in dollars', 'Includes charging-efficiency losses', 'Cost per full charge and per kWh', 'Works for home, Tesla, and public charging rates'],
  methodology: 'The calculator computes the energy delivered to the pack (battery capacity times the change in state of charge), then grosses it up by charging efficiency to find the energy actually drawn from the grid, and multiplies that by your electricity rate in dollars per kWh. This mirrors how a utility meter bills the wall energy, not the pack energy.',
  calc: {
    id: 'ev-charging-cost',
    title: 'EV Charging Cost Calculator',
    subtitle: 'The dollar cost to charge an electric car between two states of charge.',
    primaryLabel: 'Charging Cost',
    primaryUnit: '$',
    formulaText: 'Cost = (kWh added ÷ efficiency) × rate',
    note: 'Grid energy (after charging losses) times your electricity rate.',
    secondary: [
      { label: 'Energy Added to Pack', unit: 'kWh' },
      { label: 'Energy From Grid', unit: 'kWh' },
      { label: 'Cost per Full Charge', unit: '$' },
    ],
    inputs: [
      { id: 'battery', label: 'Battery Capacity', unit: 'kWh', type: 'number', value: 60, min: 0 },
      { id: 'start', label: 'Start State of Charge', unit: '%', type: 'number', value: 20, min: 0, max: 100 },
      { id: 'end', label: 'End State of Charge', unit: '%', type: 'number', value: 80, min: 0, max: 100 },
      { id: 'rate', label: 'Electricity Rate', unit: '$/kWh', type: 'number', value: 0.17, min: 0, step: 0.01 },
      { id: 'eff', label: 'Charging Efficiency', unit: '%', type: 'number', value: 90, min: 1, max: 100 },
    ],
    compute: function compute(v) {
      var kWhAdded = v.battery * (v.end - v.start) / 100;
      var gridKWh = kWhAdded / (v.eff / 100);
      var cost = gridKWh * v.rate;
      var fullGrid = v.battery / (v.eff / 100);
      var fullCost = fullGrid * v.rate;
      return {
        primary: { label: 'Charging Cost', value: cost, unit: '$', precision: 2 },
        secondary: [
          { label: 'Energy Added to Pack', value: kWhAdded, unit: 'kWh', precision: 2 },
          { label: 'Energy From Grid', value: gridKWh, unit: 'kWh', precision: 2 },
          { label: 'Cost per Full Charge', value: fullCost, unit: '$', precision: 2 },
        ],
        formula: 'Cost = (' + kWhAdded.toFixed(1) + ' ÷ ' + (v.eff / 100).toFixed(2) + ') × $' + v.rate,
        note: gridKWh.toFixed(1) + ' kWh from the grid at $' + v.rate + '/kWh.',
      };
    },
    tests: [
      { name: '60kWh 20-80 $0.17 90%', in: { battery: 60, start: 20, end: 80, rate: 0.17, eff: 90 }, expect: 6.8, tol: 0.01 },
      { name: '75kWh 10-90 $0.13 92%', in: { battery: 75, start: 10, end: 90, rate: 0.13, eff: 92 }, expect: 8.4783, tol: 0.01 },
    ],
  },
  content: [
    { type: 'section', id: 'quick-answer', icon: '⚡', heading: 'How Much Does It Cost to Charge an EV? Quick Answer', html: `<p class="content-p"><strong>To find EV charging cost, calculate the grid energy you draw and multiply by your electricity rate.</strong> A 60 kWh battery charging from 20% to 80% adds 36 kWh to the pack. At 90% charging efficiency you actually pull 40 kWh from the grid (36 ÷ 0.90). At $0.17 per kWh that session costs <strong>$6.80</strong>. The calculator above returns this along with the pack energy, grid energy, and the cost of a full charge.</p><p class="content-p">The detail most cost estimates miss is <strong>charging efficiency</strong>. Your utility meter bills the energy that flows from the wall, not the smaller amount that reaches the cells, so a naive "kWh added × rate" underestimates the bill by 8–15%. This tool grosses up the pack energy to real grid energy first, so the dollar figure matches what your electricity provider will charge. To see how long that same session takes, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a>.</p>` },
    { type: 'section', id: 'formula', icon: 'f(x)', heading: 'The EV Charging Cost Formula Explained', html: `<p class="content-p">The equation used by this calculator is:</p><div class="tool-guide-formula">Cost = (Battery kWh × (End SOC − Start SOC) ÷ 100 ÷ Efficiency) × Rate</div><p class="content-p">Working from the inside out:</p><ul><li><strong>Energy added to the pack</strong> = battery capacity × the change in state of charge. This is what powers your miles.</li><li><strong>Energy from the grid</strong> = pack energy ÷ charging efficiency. Because charging loses some energy to heat and conversion, you always pull <em>more</em> from the wall than the pack receives.</li><li><strong>Rate</strong> = your electricity price in dollars per kWh. Residential US rates average around $0.16–0.18, but time-of-use plans can drop overnight rates below $0.10 or push peak rates above $0.30.</li></ul><p class="content-p">Multiplying grid energy by the rate gives the session cost. The distinction between pack energy and grid energy is exactly why the same 36 kWh charge costs more than 36 × rate: at 90% efficiency you buy 40 kWh to deliver 36. To convert your monthly EV energy into a running cost across all sessions, pair this with the <a href="/electricity-cost-calculator/">electricity cost calculator</a>.</p>`, table: { caption: 'Cost to add 36 kWh to a pack (a 60 kWh 20→80% charge) at 90% efficiency', columns: ['Electricity Rate', 'Grid Energy', 'Session Cost', 'Typical Scenario'], rows: [['$0.10 / kWh', '40 kWh', '$4.00', 'Off-peak / cheap utility'], ['$0.13 / kWh', '40 kWh', '$5.20', 'US residential low end'], ['$0.17 / kWh', '40 kWh', '$6.80', 'US residential average'], ['$0.25 / kWh', '40 kWh', '$10.00', 'High-cost region / peak'], ['$0.40 / kWh', '40 kWh', '$16.00', 'Public DC fast charging']] } },
    { type: 'section', id: 'examples', icon: '#', heading: 'Worked Examples: What a Charge Really Costs', html: `<p class="content-p">These examples show how rate, efficiency, and charge window drive the final number.</p><p class="content-p"><strong>Example 1 — 60 kWh EV, 20→80% at home on $0.17/kWh:</strong> Pack energy = 60 × 0.60 = 36 kWh. Grid energy = 36 ÷ 0.90 = 40 kWh. Cost = 40 × $0.17 = <strong>$6.80</strong>. If you drive 3.5 miles per kWh, those 36 pack-kWh deliver about 126 miles, or roughly <strong>5.4 cents per mile</strong>.</p><p class="content-p"><strong>Example 2 — 75 kWh sedan, 10→90% on an off-peak $0.10 rate:</strong> Pack energy = 75 × 0.80 = 60 kWh. Grid energy = 60 ÷ 0.90 = 66.7 kWh. Cost = 66.7 × $0.10 = <strong>$6.67</strong>. Shifting the same charge to a $0.30 peak rate would triple it to about $20 — which is why scheduling overnight charging matters.</p><p class="content-p"><strong>Example 3 — Full charge of a 100 kWh SUV at $0.17:</strong> Grid energy = 100 ÷ 0.90 = 111 kWh. Cost = 111 × $0.17 = <strong>$18.90</strong>. Compared to a gas SUV at 22 mpg and $3.50/gal covering the same ~300 miles for roughly $48, the EV costs well under half.</p><p class="content-p"><strong>Example 4 — Public DC fast charge, 36 kWh added at $0.45/kWh billed:</strong> Public fast chargers often bill the delivered energy directly, so grid-vs-pack losses are already in their price. Cost ≈ 36 × $0.45 = <strong>$16.20</strong>. Fast charging is convenient but two to four times pricier than home charging — reserve it for trips.</p>` },
    { type: 'section', id: 'home-vs-public', icon: '⌂', heading: 'Home vs Public vs Tesla Supercharger Costs', html: `<p class="content-p">Where you charge changes the price per kWh far more than which car you drive.</p><p class="content-p"><strong>Home charging</strong> is almost always cheapest. You pay your residential rate — averaging $0.16–0.18 in the US, less on off-peak plans — with no session or idle fees. For a driver covering 12,000 miles a year at 3.5 mi/kWh, that is roughly 3,430 pack-kWh, about 3,800 grid-kWh, or around $650 a year at $0.17. Enter your own rate above to personalize it.</p><p class="content-p"><strong>Public Level 2</strong> stations range from free (some workplaces and retail) to $0.20–0.40/kWh or a per-hour fee. Per-hour billing punishes slow-charging cars, so check whether a station bills by energy or time.</p><p class="content-p"><strong>DC fast charging</strong>, including Tesla Superchargers, typically runs $0.30–0.60/kWh and may add idle fees if you stay plugged in after charging. Superchargers use dynamic pricing that varies by location and time of day. It is the road-trip option, not the daily one. To compare either against your home rate, drop the public price into the rate field and compare the session cost. For a broader energy-cost view, the <a href="/electricity-cost-calculator/">electricity cost calculator</a> handles any appliance or device.</p>` },
    { type: 'section', id: 'how-to-use', icon: '✓', heading: 'How to Use the EV Charging Cost Calculator', html: `<ol><li><strong>Enter battery capacity in kWh.</strong> Use usable capacity if you know it; the gross figure slightly overstates cost.</li><li><strong>Set the start and end state of charge.</strong> Match the percentages you actually charge between — a 20→80% daily window, or 10→100% before a trip.</li><li><strong>Enter your electricity rate in $/kWh.</strong> Find it on your utility bill (total bill ÷ kWh used is the all-in rate). Use your off-peak rate if you charge overnight.</li><li><strong>Set charging efficiency.</strong> Use 90% for home Level 2 AC charging. For public DC chargers that bill delivered energy, set efficiency to 100% because their price already covers losses.</li></ol><p class="content-p">The result shows session cost, pack and grid energy, and the cost of a full charge. Adjust the rate to compare utility plans, or the SOC window to see how a smaller daily top-up saves money. To turn these costs into a per-mile figure, divide the pack kWh by your car's miles per kWh from the <a href="/ev-range-calculator/">EV range calculator</a>.</p>` },
    { type: 'section', id: 'vs-gas', icon: '⛽', heading: 'EV Charging Cost vs Gasoline: The Real Comparison', html: `<p class="content-p">The fairest EV-versus-gas comparison is cost per mile, and the EV usually wins by a wide margin on home electricity.</p><p class="content-p"><strong>EV side.</strong> Take grid energy per session, multiply by rate for the dollar cost, then divide by the miles that charge delivers. Our 60 kWh 20→80% example bought 40 grid-kWh for $6.80 and delivered about 126 miles at 3.5 mi/kWh — roughly <strong>5.4 cents per mile</strong>. On a $0.10 off-peak rate that falls to about 3.2 cents per mile.</p><p class="content-p"><strong>Gas side.</strong> A 30 mpg car at $3.50 per gallon costs $3.50 ÷ 30 = <strong>11.7 cents per mile</strong>. A 22 mpg SUV at the same price costs about 15.9 cents per mile.</p><p class="content-p">So home charging typically costs one-third to one-half of gasoline per mile, and the gap widens on cheap overnight electricity or when gas prices spike. The equation flips only when charging exclusively at premium DC fast chargers — at $0.50/kWh the EV can approach or exceed an efficient hybrid's fuel cost. The lesson is the same as with charge time: home charging is the foundation, fast charging is the convenience. Model your own numbers by pairing this tool with the <a href="/ev-range-calculator/">EV range calculator</a> for miles per kWh.</p>`, table: { caption: 'Cost per mile: EV vs gasoline (illustrative)', columns: ['Vehicle', 'Energy Price', 'Efficiency', 'Cost per Mile'], rows: [['EV (off-peak home)', '$0.10/kWh', '3.5 mi/kWh', '≈ 3.2¢'], ['EV (average home)', '$0.17/kWh', '3.5 mi/kWh', '≈ 5.4¢'], ['EV (DC fast)', '$0.45/kWh', '3.5 mi/kWh', '≈ 14.3¢'], ['Hybrid car', '$3.50/gal', '45 mpg', '≈ 7.8¢'], ['Gas sedan', '$3.50/gal', '30 mpg', '≈ 11.7¢'], ['Gas SUV', '$3.50/gal', '22 mpg', '≈ 15.9¢']] } },
    { type: 'section', id: 'save', icon: '↓', heading: 'How to Lower Your EV Charging Costs', html: `<p class="content-p">Several levers cut the running cost of an EV, and the calculator lets you test each one.</p><ul><li><strong>Charge on a time-of-use plan.</strong> Overnight off-peak rates are often half the peak price. Scheduling charging for the early hours can nearly halve the cost figure above with no change to your driving.</li><li><strong>Charge at home, not at DC fast chargers.</strong> Public fast charging is typically two to four times the home rate. Reserve it for trips.</li><li><strong>Stay in the 20–80% window daily.</strong> Smaller, more frequent top-ups avoid the slower, sometimes pricier end of the charge and are easier on the battery.</li><li><strong>Add solar.</strong> Charging from rooftop solar during the day can drop the effective rate toward zero. Model your generation with a solar calculator and use the surplus for charging.</li><li><strong>Improve efficiency.</strong> Gentle driving, correct tire pressure, and pre-conditioning while plugged in all raise miles per kWh, lowering cost per mile.</li></ul><p class="content-p">Because the cost scales directly with both the rate and the grid energy, the two biggest wins are a cheaper rate and charging only what you need. To size the home charger that makes overnight charging practical, use the <a href="/home-ev-charger-amp-calculator/">home EV charger amp calculator</a>.</p><p class="content-p">One more lever is worth naming: demand charges and fixed fees on some commercial or dedicated EV rate plans. A utility may offer a low per-kWh EV rate but attach a monthly service charge or a demand charge based on your peak draw. For a home Level 2 charger the demand component is usually small, but if you install a very high-power charger and run it alongside other big loads, staggering start times can trim the peak. Always model the all-in rate — energy plus any per-kWh delivery adder — in the rate field, because that combined figure is what actually multiplies your grid kWh into the bill.</p>` },
    { type: 'section', id: 'mistakes', icon: '!', heading: 'Common Mistakes in EV Cost Estimates', html: `<ul><li><strong>Multiplying pack kWh by rate directly.</strong> This ignores charging losses; you buy 8–15% more grid energy than the pack receives on AC.</li><li><strong>Using the wrong rate.</strong> Marginal off-peak, average, and peak rates differ enormously. Use the rate that applies when you actually charge.</li><li><strong>Forgetting fees.</strong> Public stations may add session, idle, or per-minute fees on top of the per-kWh price.</li><li><strong>Comparing full charges to partial gas fill-ups.</strong> Compare cost per mile, not per "tank," for a fair EV-vs-gas picture.</li><li><strong>Assuming DC fast charging costs the same as home.</strong> It usually costs two to four times more per kWh.</li></ul><p class="content-p">For a complete session picture, run this alongside the <a href="/ev-charging-time-calculator/">EV charging time calculator</a> to see both the hours and the dollars for the same charge.</p>` },
  ],
  faq: [
    { q: 'How much does it cost to charge an EV at home?', a: 'For a 60 kWh EV charging 20→80% (36 kWh to the pack, about 40 kWh from the grid at 90% efficiency), the cost is around $6.80 at the US average $0.17/kWh, or about $4.00 on a $0.10 off-peak rate. A full charge of that battery costs roughly $11.30 at average rates. Enter your own rate and battery size above for an exact figure.' },
    { q: 'How much does it cost to charge a Tesla?', a: 'At home it is the same math as any EV: for a 75 kWh Model charging 20→80% (about 45 kWh to the pack, 50 kWh from the grid), roughly $8.50 at $0.17/kWh. Tesla Superchargers use dynamic pricing, typically $0.30–0.60/kWh, so the same charge on a Supercharger might cost $15–27 plus any idle fees. Home charging is far cheaper for daily use.' },
    { q: 'Why does the calculator show more grid energy than pack energy?', a: 'Charging is not perfectly efficient. AC charging loses 8–15% of the energy to heat and AC-to-DC conversion in the onboard charger, so you draw more from the wall than reaches the battery. At 90% efficiency, adding 36 kWh to the pack pulls 40 kWh from the grid. Your utility bills the grid energy, so we use that for the cost.' },
    { q: 'Is it cheaper to charge an EV or fill a gas car?', a: 'Home charging is usually one-third to one-half the per-mile cost of gasoline. An EV at 3.5 mi/kWh and $0.17/kWh costs about 5.4 cents per mile; a 30 mpg gas car at $3.50/gal costs about 11.7 cents per mile. The advantage shrinks or disappears only if you charge exclusively at premium DC fast chargers.' },
    { q: 'What electricity rate should I enter?', a: 'Use the rate that applies when you charge. For overnight home charging, use your off-peak time-of-use rate; otherwise use your all-in residential rate (total bill divided by kWh used, which includes delivery charges). US residential rates average around $0.16–0.18/kWh but vary widely by state and plan.' },
    { q: 'Does fast charging cost more than home charging?', a: 'Yes, typically two to four times more per kWh. Home electricity averages $0.16–0.18/kWh, while DC fast charging often runs $0.30–0.60/kWh plus possible idle or session fees. Fast charging trades cost for speed, so it is best reserved for road trips while daily charging happens at home.' },
    { q: 'How do I calculate my cost per mile?', a: 'Take the grid energy for a charge, multiply by your rate to get the dollar cost, then divide by the miles that charge delivers (pack kWh times your miles per kWh). For example, 40 grid-kWh at $0.17 is $6.80, and 36 pack-kWh at 3.5 mi/kWh gives 126 miles, so about 5.4 cents per mile. Use the EV range calculator to find your miles per kWh.' },
  ],
  related: [
    { href: '/ev-charging-time-calculator/', badge: 'h', title: 'EV Charging Time Calculator', desc: 'How long a charge session takes' },
    { href: '/electricity-cost-calculator/', badge: 'kWh', title: 'Electricity Cost Calculator', desc: 'Cost of energy for any device' },
    { href: '/ev-range-calculator/', badge: 'mi', title: 'EV Range Calculator', desc: 'Miles per kWh and range' },
    { href: '/home-ev-charger-amp-calculator/', badge: 'A', title: 'Home EV Charger Amp Calculator', desc: 'Size your charging circuit' },
    { href: '/battery-charge-time-calculator/', badge: 'Ah', title: 'Battery Charge Time Calculator', desc: 'Charge time for 12 V batteries' },
    { href: '/battery-runtime-calculator/', badge: 'h', title: 'Battery Runtime Calculator', desc: 'How long a battery lasts' },
  ],
};

const batteryChargeTime = {
  slug: 'battery-charge-time-calculator',
  category: 'EV & Charging Calculators',
  kicker: 'Battery charging time planning',
  h1: 'Battery Charge Time Calculator',
  title: 'Battery Charge Time Calculator — How Long to Charge a Battery | Ampstowatt',
  metaDesc: 'Calculate how long it takes to charge a battery. Enter amp-hours, charger current, and efficiency to get charge time in hours for lead-acid, AGM, and lithium batteries.',
  keywords: ['battery charge time calculator', 'how long to charge a battery', 'battery charging time calculator', 'lead acid charge time calculator', '12v battery charge time', 'charge time calculator amps'],
  formulaPill: 'Time (h) = (Ah ÷ efficiency) ÷ Charger A',
  lead: 'Estimate <strong>how long it takes to charge a battery</strong> from a charger current in amps. This battery charge time calculator adds a charging-efficiency factor so lead-acid, AGM, gel, and lithium batteries all get a realistic time in hours — not the optimistic Ah ÷ amps shortcut.',
  reviewed: 'September 5, 2026',
  featureList: ['Charge time in hours and minutes', 'Efficiency factor for lead-acid vs lithium', 'Charge rate (C-rate) output', 'Works for 12 V, 24 V, and 48 V banks'],
  methodology: 'The calculator divides amp-hours by the charge efficiency to find the actual amp-hours the charger must supply (lead-acid needs roughly 1.15–1.2× its rated capacity to fully recharge), then divides by the charger current in amps to return charge time. It also reports the C-rate — charger amps divided by capacity — to flag charging that is too fast or too slow for the chemistry.',
  calc: {
    id: 'battery-charge-time',
    title: 'Battery Charge Time Calculator',
    subtitle: 'How long to charge a battery from a charger current in amps.',
    primaryLabel: 'Charge Time',
    primaryUnit: 'hours',
    formulaText: 'Time = (Ah ÷ efficiency) ÷ charger amps',
    note: 'Amp-hours to replace (with charge losses) divided by charger current.',
    secondary: [
      { label: 'Charge Time', unit: 'min' },
      { label: 'Charge Rate', unit: 'C' },
      { label: 'Ah Supplied', unit: 'Ah' },
    ],
    inputs: [
      { id: 'capacity', label: 'Battery Capacity', unit: 'Ah', type: 'number', value: 100, min: 0 },
      { id: 'current', label: 'Charger Current', unit: 'A', type: 'number', value: 10, min: 0, step: 0.1 },
      { id: 'eff', label: 'Charge Efficiency', unit: '%', type: 'number', value: 85, min: 1, max: 100 },
    ],
    compute: function compute(v) {
      var ahSupplied = v.capacity / (v.eff / 100);
      var hours = ahSupplied / v.current;
      var cRate = v.current / v.capacity;
      return {
        primary: { label: 'Charge Time', value: hours, unit: 'hours', precision: 2 },
        secondary: [
          { label: 'Charge Time', value: hours * 60, unit: 'min', precision: 0 },
          { label: 'Charge Rate', value: cRate, unit: 'C', precision: 3 },
          { label: 'Ah Supplied', value: ahSupplied, unit: 'Ah', precision: 1 },
        ],
        formula: 'Time = (' + v.capacity + ' ÷ ' + (v.eff / 100).toFixed(2) + ') ÷ ' + v.current + ' A',
        note: ahSupplied.toFixed(0) + ' Ah supplied at ' + cRate.toFixed(2) + 'C charge rate.',
      };
    },
    tests: [
      { name: '100Ah 10A 85%', in: { capacity: 100, current: 10, eff: 85 }, expect: 11.7647, tol: 0.01 },
      { name: '200Ah 40A 90%', in: { capacity: 200, current: 40, eff: 90 }, expect: 5.5556, tol: 0.01 },
    ],
  },
  content: [
    { type: 'section', id: 'quick-answer', icon: '⚡', heading: 'How Long to Charge a Battery? Quick Answer', html: `<p class="content-p"><strong>To find battery charge time, divide the amp-hours you need to replace by the charger current in amps, then add for charging losses.</strong> A fully discharged 100Ah battery on a 10A charger would take 10 hours in a perfect world, but lead-acid charging is only about 85% efficient, so it must actually receive around 118 Ah. That pushes the real charge time to about <strong>11.8 hours</strong>. The calculator above does this instantly and also shows the C-rate and amp-hours supplied.</p><p class="content-p">The naive "Ah ÷ amps" answer is always too optimistic for lead-acid because some charge energy is lost to heat and gassing, especially in the final absorption stage. Lithium (LiFePO4) is far more efficient — often 95–99% — so its charge time is close to the ideal. Setting the efficiency input correctly for your chemistry is what turns a rough guess into a plan you can schedule around. For electric-car packs measured in kWh, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a> instead.</p>` },
    { type: 'section', id: 'formula', icon: 'f(x)', heading: 'The Battery Charge Time Formula Explained', html: `<p class="content-p">The equation used by this calculator is:</p><div class="tool-guide-formula">Charge Time (hours) = (Amp-hours ÷ Charge Efficiency) ÷ Charger Current (A)</div><p class="content-p">Each term matters:</p><ul><li><strong>Amp-hours (Ah)</strong> — the capacity you need to replace. For a full recharge use the battery's rated Ah; for a partial recharge use only the Ah that were removed.</li><li><strong>Charge efficiency (η)</strong> — the fraction of supplied charge that actually gets stored. Lead-acid is roughly 80–85% (so it needs a charge factor of about 1.15–1.2× capacity); AGM is a little better; LiFePO4 lithium is 95–99%.</li><li><strong>Charger current (A)</strong> — the charger's output in amps. A 10A charger delivers up to 10A, but multi-stage chargers taper the current in the absorption and float stages, so real charge time runs longer than this simple division near the top.</li></ul><p class="content-p">Dividing amp-hours by amps yields hours because an amp-hour is, by definition, one amp flowing for one hour. The efficiency term is what separates lead-acid (slow, lossy) from lithium (fast, efficient). To convert amp-hours into stored energy for runtime planning, use the <a href="/battery-runtime-calculator/">battery runtime calculator</a>.</p>`, table: { caption: 'Charge efficiency and recommended charge rate by chemistry', columns: ['Battery Type', 'Charge Efficiency', 'Charge Factor', 'Typical Max Charge Rate'], rows: [['Flooded Lead-Acid', '75–85%', '≈ 1.2×', '0.1–0.2C (C/10–C/5)'], ['AGM Lead-Acid', '85–90%', '≈ 1.15×', '0.2–0.3C'], ['Gel Lead-Acid', '85–90%', '≈ 1.15×', '0.1–0.2C'], ['LiFePO4 (Lithium)', '95–99%', '≈ 1.02×', '0.5–1C (some 1C+)'], ['Li-ion (NMC)', '95–99%', '≈ 1.02×', '0.5–1C']] } },
    { type: 'section', id: 'examples', icon: '#', heading: 'Worked Examples: Real Battery Charge Times', html: `<p class="content-p">These examples show how capacity, charger size, and chemistry change the answer.</p><p class="content-p"><strong>Example 1 — 100Ah flooded lead-acid on a 10A charger:</strong> Ah supplied = 100 ÷ 0.85 = 118 Ah. Time = 118 ÷ 10 = <strong>11.8 hours</strong>. The C-rate is 10 ÷ 100 = 0.1C (C/10), a gentle, healthy charge rate for lead-acid. In practice a three-stage charger adds an hour or two in absorption, so plan for overnight.</p><p class="content-p"><strong>Example 2 — 200Ah AGM bank on a 40A charger:</strong> Ah supplied = 200 ÷ 0.90 = 222 Ah. Time = 222 ÷ 40 = <strong>5.6 hours</strong>. The C-rate is 40 ÷ 200 = 0.2C, near the top of the comfortable range for AGM. A larger charger would be faster but risks heat.</p><p class="content-p"><strong>Example 3 — 100Ah LiFePO4 on a 50A charger:</strong> Ah supplied = 100 ÷ 0.98 = 102 Ah. Time = 102 ÷ 50 = <strong>2.04 hours</strong>. The C-rate is 0.5C, well within LiFePO4 limits. Lithium's high efficiency and high charge-rate tolerance let it recharge in a fraction of the time lead-acid needs.</p><p class="content-p"><strong>Example 4 — Partial recharge, 100Ah lead-acid down 40Ah, 10A charger:</strong> You only need to replace 40Ah, so Ah supplied = 40 ÷ 0.85 = 47 Ah. Time = 47 ÷ 10 = <strong>4.7 hours</strong>. Entering the amp-hours actually used, rather than full capacity, gives the right answer for daily top-ups.</p>` },
    { type: 'section', id: 'c-rate', icon: 'C', heading: 'Understanding the C-Rate and Why It Limits Charge Speed', html: `<p class="content-p">The <strong>C-rate</strong> expresses charge or discharge current relative to capacity: 1C is a current equal to the amp-hour rating, 0.5C is half that, C/10 (0.1C) is a tenth. A 100Ah battery charged at 20A is charging at 0.2C. The calculator reports the C-rate so you can immediately see whether your charger is matched to the chemistry.</p><p class="content-p"><strong>Lead-acid</strong> prefers a slow charge — roughly 0.1–0.2C. Push it faster and it heats, gasses, and loses water and cycle life. This is why a 100Ah lead-acid battery is happiest on a 10–20A charger, taking most of a day for a full cycle.</p><p class="content-p"><strong>Lithium (LiFePO4)</strong> accepts far higher rates, commonly 0.5–1C and sometimes more, because it has low internal resistance and an efficient charge acceptance. A 100Ah LiFePO4 can often take a 50–100A charger, recharging in one to two hours. That charge-speed advantage, on top of its efficiency, is a major reason lithium dominates modern solar, RV, and marine systems.</p><p class="content-p">A charger that is too small wastes time; one that is too large for the chemistry wastes battery life. The C-rate output is your quick check that the two are matched. For sizing the stored energy behind these amp-hours, see the <a href="/battery-runtime-calculator/">battery runtime calculator</a>.</p>` },
    { type: 'section', id: 'how-to-use', icon: '✓', heading: 'How to Use the Battery Charge Time Calculator', html: `<ol><li><strong>Enter the amp-hours to replace.</strong> For a full recharge, use the battery's rated Ah. For a partial recharge, enter only the Ah you removed (capacity × depth of discharge).</li><li><strong>Enter the charger current in amps.</strong> Use the charger's rated output. If you only know watts, divide by charging voltage to get amps.</li><li><strong>Set the charge efficiency.</strong> Use 80–85% for flooded lead-acid, 85–90% for AGM or gel, and 95–99% for LiFePO4 lithium.</li></ol><p class="content-p">The result shows charge time in hours and minutes, the C-rate, and the amp-hours the charger must supply. Watch the C-rate: if it is above about 0.2C for lead-acid, consider a smaller charger; if it is well below 0.1C for a large lithium bank, a bigger charger would save hours. For multi-battery banks, add the amp-hours of parallel batteries together. To plan an EV pack instead, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a>, and to size a charging circuit, the <a href="/home-ev-charger-amp-calculator/">home EV charger amp calculator</a>.</p>` },
    { type: 'section', id: 'stages', icon: '⇥', heading: 'Why Multi-Stage Chargers Take Longer at the Top', html: `<p class="content-p">The simple formula assumes constant current, but modern smart chargers deliver charge in stages, and the later stages are slow by design. Understanding this explains why the last 20% always takes longer than the math suggests.</p><p class="content-p"><strong>Bulk stage.</strong> The charger delivers its full rated current until the battery reaches roughly 80% of capacity. This is the fast part, and it closely matches the Ah ÷ amps calculation. Most of the charge goes in here.</p><p class="content-p"><strong>Absorption stage.</strong> The charger holds a constant voltage while the current tapers down. This tops off the final 15–20% and can take several hours for lead-acid, because forcing the last charge in too fast causes gassing and heat. Lithium absorbs much faster here.</p><p class="content-p"><strong>Float stage.</strong> Once full, the charger drops to a low maintenance voltage to hold the battery at 100% without overcharging. No meaningful capacity is added; this stage just maintains the battery.</p><p class="content-p">Because absorption tapers the current, real full-charge time for lead-acid is often 20–40% longer than the constant-current formula predicts. Treat the calculator's result as the bulk-charge estimate, then add time for the top-off — or set a slightly lower efficiency to build the taper into your plan.</p>` },
    { type: 'section', id: 'reference', icon: '⏱', heading: 'Battery Charge Time Reference Table', html: `<p class="content-p">The table shows approximate full-charge time for common battery and charger combinations, using 85% efficiency for lead-acid and 98% for lithium. These are bulk-stage estimates; add time for absorption on lead-acid.</p><p class="content-p">Notice how a bigger charger cuts time proportionally until the C-rate gets too high for the chemistry. For lead-acid, a 20A charger on a 100Ah battery (0.2C) is about the practical floor for charge time without stressing the battery; lithium's tolerance for higher rates is what unlocks the sub-two-hour recharges.</p>`, table: { caption: 'Approximate full-charge time (hours)', columns: ['Battery', 'Charger 10 A', 'Charger 20 A', 'Charger 40 A', 'Chemistry'], rows: [['50 Ah', '5.9 h', '2.9 h', '1.5 h', 'Lead-acid (85%)'], ['100 Ah', '11.8 h', '5.9 h', '2.9 h', 'Lead-acid (85%)'], ['100 Ah', '10.2 h', '5.1 h', '2.6 h', 'LiFePO4 (98%)'], ['200 Ah', '23.5 h', '11.8 h', '5.9 h', 'Lead-acid (85%)'], ['200 Ah', '20.4 h', '10.2 h', '5.1 h', 'LiFePO4 (98%)']] } },
    { type: 'section', id: 'series-parallel', icon: '⇄', heading: 'Charging Banks: Series, Parallel, and Solar', html: `<p class="content-p">When you charge more than one battery, how they are wired decides what amp-hours and voltage you enter, and it changes the charge time.</p><p class="content-p"><strong>Parallel banks</strong> add amp-hours at the same voltage. Two 100Ah 12V batteries in parallel form a 200Ah 12V bank, so enter 200Ah. With a 40A charger that is 200 ÷ 0.85 ÷ 40 ≈ 5.9 hours, the same as one big 200Ah battery. The charger current is shared across the batteries, so each sees only 20A — a gentle 0.2C.</p><p class="content-p"><strong>Series banks</strong> add voltage while amp-hours stay the same. Two 100Ah 12V batteries in series make a 24V 100Ah bank; you still enter 100Ah, but you need a 24V charger. Charge time is unchanged from a single 100Ah battery because the amp-hours to replace have not changed — only the voltage did.</p><p class="content-p"><strong>Solar charging</strong> complicates the picture because the current varies with sunlight. A 400W solar array on a 12V bank through an MPPT controller might deliver 25–30A at midday but far less morning and evening. For a rough estimate, use the array's average daytime current as the charger current, then expect real charging to take longer on cloudy days. A charge controller also holds the battery in absorption and float just like a smart charger, so the top-off taper still applies. To size the array and storage together, the amp-hours here feed directly into off-grid and solar battery planning.</p>` },
    { type: 'section', id: 'mistakes', icon: '!', heading: 'Common Mistakes in Charge Time Estimates', html: `<ul><li><strong>Using Ah ÷ amps with no efficiency factor.</strong> Lead-acid needs about 15–20% more charge than its rating, so the naive number is always too short.</li><li><strong>Charging lead-acid too fast.</strong> A charger above about 0.2C causes heat and gassing; the C-rate output warns you.</li><li><strong>Ignoring the absorption taper.</strong> The last 15–20% charges slowly on lead-acid; add time or lower the efficiency input.</li><li><strong>Entering full capacity for a partial recharge.</strong> Enter only the amp-hours you actually used for daily top-ups.</li><li><strong>Mixing amp-hours and watt-hours.</strong> This tool uses amp-hours and amps; for kWh EV packs use the EV charging time calculator.</li></ul><p class="content-p">For runtime after charging, and to convert capacity into stored energy, pair this with the <a href="/battery-runtime-calculator/">battery runtime calculator</a> and the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a> for the cost side.</p>` },
  ],
  faq: [
    { q: 'How long does it take to charge a 100Ah battery?', a: 'On a 10A charger, a fully discharged 100Ah lead-acid battery takes about 11.8 hours once you account for roughly 85% charge efficiency (it must receive about 118 Ah). A 100Ah LiFePO4 lithium battery on the same charger takes about 10.2 hours thanks to higher efficiency, and it can safely use a much larger charger to cut that to one or two hours.' },
    { q: 'How do I calculate battery charging time?', a: 'Divide the amp-hours you need to replace by the charger current in amps, then divide by the charge efficiency. For a full 100Ah lead-acid battery at 85% efficiency on a 10A charger: 100 ÷ 0.85 ÷ 10 = about 11.8 hours. For a partial recharge, use only the amp-hours removed instead of full capacity.' },
    { q: 'Why does my battery take longer to charge than the formula says?', a: 'Smart chargers taper the current in the absorption and float stages, so the last 15–20% charges slowly to avoid overheating and gassing — especially on lead-acid. Cold temperatures, an aging battery, and a charger that cannot sustain its rated current also add time. The formula gives the bulk-stage estimate; add time for the top-off.' },
    { q: 'What is the C-rate for charging a battery?', a: 'The C-rate is the charge current relative to capacity. A 100Ah battery charged at 20A is at 0.2C (C/5); at 10A it is 0.1C (C/10). Lead-acid prefers 0.1–0.2C; lithium tolerates 0.5–1C or more. The calculator reports the C-rate so you can check that your charger is matched to the battery chemistry.' },
    { q: 'What charge efficiency should I use?', a: 'Use 80–85% for flooded lead-acid, 85–90% for AGM or gel, and 95–99% for LiFePO4 lithium. The efficiency represents the fraction of supplied charge that gets stored; the rest is lost to heat and, in lead-acid, gassing during the final charge stage. Lower efficiency means a longer charge time.' },
    { q: 'Can I charge a battery faster with a bigger charger?', a: 'Up to a point. A larger charger cuts charge time proportionally until the C-rate exceeds what the chemistry can handle. Lead-acid should stay near 0.1–0.2C, so a 100Ah lead-acid battery tops out around a 20A charger. Lithium accepts 0.5–1C, so a 100Ah LiFePO4 can use a 50–100A charger and recharge in one to two hours.' },
    { q: 'How is charging a 12V battery different from charging an EV?', a: 'The physics are the same, but the units differ. A 12V auxiliary or deep-cycle battery is rated in amp-hours and charged in amps, so this calculator uses Ah ÷ amps. An EV traction pack is rated in kilowatt-hours and charged in kilowatts, so use the EV charging time calculator, which divides kWh by kW.' },
  ],
  related: [
    { href: '/battery-runtime-calculator/', badge: 'h', title: 'Battery Runtime Calculator', desc: 'How long a battery lasts under load' },
    { href: '/ev-charging-time-calculator/', badge: 'kW', title: 'EV Charging Time Calculator', desc: 'Charge time for electric-car packs' },
    { href: '/ev-charging-cost-calculator/', badge: '$', title: 'EV Charging Cost Calculator', desc: 'Cost to charge an EV' },
    { href: '/home-ev-charger-amp-calculator/', badge: 'A', title: 'Home EV Charger Amp Calculator', desc: 'Size a charging circuit' },
    { href: '/amp-hours-to-watt-hours/', badge: 'Wh', title: 'Amp Hours to Watt Hours', desc: 'Convert Ah into energy' },
    { href: '/electricity-cost-calculator/', badge: 'kWh', title: 'Electricity Cost Calculator', desc: 'Cost of energy per kWh' },
  ],
};

const homeEvChargerAmp = {
  slug: 'home-ev-charger-amp-calculator',
  category: 'EV & Charging Calculators',
  kicker: 'EV charger circuit sizing',
  h1: 'Home EV Charger Amp Calculator',
  title: 'Home EV Charger Amp Calculator — Amps & Breaker Size | Ampstowatt',
  metaDesc: 'Calculate the amps and breaker size for a home EV charger. Enter charger power and voltage to get charging current, the NEC-required breaker, wire gauge guidance, and miles per hour.',
  keywords: ['home ev charger amp calculator', 'how many amps to charge ev', 'ev charger circuit', 'ev charger breaker size', 'ev charger amps calculator', 'level 2 charger amps'],
  formulaPill: 'Amps = Charger W ÷ Voltage · Breaker = Amps × 1.25',
  lead: 'Size the circuit for a <strong>home EV charger</strong> the right way. This home EV charger amp calculator converts charger power and voltage into charging current, then applies the NEC 125% continuous-load rule to give the correct breaker size, wire guidance, and the miles of range you add per hour.',
  reviewed: 'September 5, 2026',
  featureList: ['Charging current in amps', 'NEC-compliant breaker size (125% rule)', 'Wire gauge guidance', 'Estimated miles added per hour'],
  methodology: 'The calculator divides charger power in watts by the circuit voltage to find continuous charging current, then applies the National Electrical Code 125% continuous-load factor (NEC 625.41 and 210.20) and rounds up to the next standard breaker size. Wire guidance follows common 75°C copper ampacity for the resulting breaker, and range-per-hour uses a typical EV efficiency of about 3.5 miles per kWh.',
  calc: {
    id: 'home-ev-charger-amp',
    title: 'Home EV Charger Amp Calculator',
    subtitle: 'Amps, breaker size, and wire for a home EV charging circuit.',
    primaryLabel: 'Charging Current',
    primaryUnit: 'A',
    formulaText: 'Amps = Charger Watts ÷ Voltage',
    note: 'Continuous current; breaker sized at 125% per NEC.',
    secondary: [
      { label: 'Required Breaker', unit: 'A' },
      { label: 'Continuous Load (125%)', unit: 'A' },
      { label: 'Range Added', unit: 'mi/hr' },
    ],
    inputs: [
      { id: 'power', label: 'Charger Power', unit: 'kW', type: 'number', value: 11.5, min: 0, step: 0.1 },
      { id: 'voltage', label: 'Circuit Voltage', unit: 'V', type: 'select', value: '240', options: [{ v: '240', t: '240 V (split-phase home)' }, { v: '208', t: '208 V (commercial)' }, { v: '120', t: '120 V (Level 1)' }] },
    ],
    compute: function compute(v) {
      var watts = v.power * 1000;
      var volts = parseFloat(v.voltage);
      var amps = watts / volts;
      var continuous = amps * 1.25;
      var std = [15, 20, 30, 40, 50, 60, 70, 80, 90, 100];
      var breaker = std[std.length - 1];
      for (var i = 0; i < std.length; i++) { if (std[i] >= continuous) { breaker = std[i]; break; } }
      var miles = v.power * 3.5;
      return {
        primary: { label: 'Charging Current', value: amps, unit: 'A', precision: 1 },
        secondary: [
          { label: 'Required Breaker', value: breaker, unit: 'A', precision: 0 },
          { label: 'Continuous Load (125%)', value: continuous, unit: 'A', precision: 1 },
          { label: 'Range Added', value: miles, unit: 'mi/hr', precision: 0 },
        ],
        formula: 'Amps = ' + watts + ' W ÷ ' + volts + ' V = ' + amps.toFixed(1) + ' A',
        note: amps.toFixed(1) + ' A × 1.25 = ' + continuous.toFixed(1) + ' A → ' + breaker + ' A breaker.',
      };
    },
    tests: [
      { name: '11.5kW at 240V', in: { power: 11.5, voltage: '240' }, expect: 47.9167, tol: 0.01 },
      { name: '7.4kW at 240V', in: { power: 7.4, voltage: '240' }, expect: 30.8333, tol: 0.01 },
    ],
  },
  content: [
    { type: 'section', id: 'quick-answer', icon: '⚡', heading: 'How Many Amps Does a Home EV Charger Need? Quick Answer', html: `<p class="content-p"><strong>To size a home EV charger circuit, divide the charger's power by the voltage to get charging amps, then multiply by 1.25 for the breaker.</strong> An 11.5 kW charger on a 240 V circuit draws 11,500 ÷ 240 = about <strong>47.9 A</strong>. EV charging is a continuous load, so the NEC requires the circuit to be rated at 125% of that — 47.9 × 1.25 ≈ 60 A — meaning a <strong>60 A breaker</strong> with wiring rated for it. The calculator above returns the amps, breaker, continuous load, and miles added per hour instantly.</p><p class="content-p">The 125% rule is the single most important detail and the one DIYers miss. A charger that draws 48 A continuously cannot sit on a 50 A breaker; it needs a 60 A breaker and 6 AWG copper wire. Getting this right keeps the circuit safe, code-compliant, and able to run at full power for hours without nuisance trips. Once the circuit is sized, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a> to see how long each charge takes.</p>` },
    { type: 'section', id: 'formula', icon: 'f(x)', heading: 'The EV Charger Amp and Breaker Formula', html: `<p class="content-p">Two equations size the circuit:</p><div class="tool-guide-formula">Charging Amps = Charger Watts ÷ Voltage<br>Breaker Size = Charging Amps × 1.25 (rounded up to a standard size)</div><p class="content-p">Here is what each piece means:</p><ul><li><strong>Charger watts</strong> — the charger's rated output power. A "11.5 kW" charger is 11,500 W; a "7.4 kW" charger is 7,400 W.</li><li><strong>Voltage</strong> — 240 V for a standard North American split-phase home circuit, 208 V for commercial three-phase, or 120 V for a Level 1 outlet. Lower voltage means higher current for the same power.</li><li><strong>The 1.25 factor</strong> — NEC 625.41 and 210.20(A) classify EV charging as a continuous load (three hours or more), so the branch circuit and overcurrent device must be rated at least 125% of the load. Equivalently, the charger may draw no more than 80% of the breaker rating.</li></ul><p class="content-p">So a 48 A charger needs a 60 A circuit (48 ÷ 0.8 = 60), and a 40 A charger needs a 50 A circuit. Rounding is always up to the next standard breaker — 15, 20, 30, 40, 50, 60 A and so on. For the reverse question of how many watts a given charger amperage represents, see the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a> to translate that energy into dollars.</p>`, table: { caption: 'Common home EV charger sizes and required circuits (240 V)', columns: ['Charger Power', 'Charging Amps', 'Breaker (125%)', 'Copper Wire (75°C)', 'Range/hr*'], rows: [['3.8 kW', '16 A', '20 A', '12 AWG', '~13 mi'], ['7.7 kW', '32 A', '40 A', '8 AWG', '~27 mi'], ['9.6 kW', '40 A', '50 A', '6 AWG', '~34 mi'], ['11.5 kW', '48 A', '60 A', '6 AWG', '~40 mi'], ['19.2 kW', '80 A', '100 A', '3 AWG', '~67 mi']] } },
    { type: 'section', id: 'examples', icon: '#', heading: 'Worked Examples: Sizing a Home Charging Circuit', html: `<p class="content-p">These examples walk through the full sizing math for common installs.</p><p class="content-p"><strong>Example 1 — 11.5 kW charger, 240 V:</strong> Amps = 11,500 ÷ 240 = 47.9 A. Continuous rating = 47.9 × 1.25 = 59.9 A, rounding up to a <strong>60 A breaker</strong>. This needs 6 AWG copper (or 4 AWG for long runs) and delivers about 40 miles of range per hour — one of the most popular high-power home setups.</p><p class="content-p"><strong>Example 2 — 7.4 kW charger, 240 V:</strong> Amps = 7,400 ÷ 240 = 30.8 A. Continuous = 30.8 × 1.25 = 38.5 A, rounding up to a <strong>40 A breaker</strong> with 8 AWG copper. It adds about 26 miles per hour — plenty for a typical commuter and a common, affordable install.</p><p class="content-p"><strong>Example 3 — 9.6 kW charger, 240 V:</strong> Amps = 9,600 ÷ 240 = 40 A. Continuous = 40 × 1.25 = 50 A, needing a <strong>50 A breaker</strong> and 6 AWG copper. This 40 A charger is a sweet spot: strong charging speed on a widely available circuit size.</p><p class="content-p"><strong>Example 4 — 1.4 kW Level 1, 120 V:</strong> Amps = 1,440 ÷ 120 = 12 A. Continuous = 12 × 1.25 = 15 A, so a standard <strong>15–20 A</strong> household circuit works, but it adds only about 5 miles per hour. This is the plug-in-anywhere backup, not a daily solution for a large battery.</p>` },
    { type: 'section', id: 'wire', icon: '⌁', heading: 'Wire Gauge, Breaker, and the 80% Rule', html: `<p class="content-p">Choosing the wire is as important as choosing the breaker, and both follow from the charging amps. The wire must safely carry the continuous current, and the breaker protects the wire — not the charger.</p><p class="content-p">Because EV charging is continuous, the practical rule is the <strong>80% rule</strong>: a charger may draw no more than 80% of the circuit's rating. A 50 A circuit supports a 40 A charger; a 60 A circuit supports a 48 A charger. This is the same 125% factor viewed from the other side (1 ÷ 1.25 = 0.8).</p><p class="content-p">Copper wire ampacity at the common 75°C column sets the minimum gauge: 12 AWG for 20 A, 10 AWG for 30 A, 8 AWG for 40 A, 6 AWG for 50–60 A, 4 AWG for 70 A, and 3 AWG for 100 A. Long runs need an upsize to counter voltage drop — a factor the dedicated <a href="/voltage-drop-calculator/">voltage drop calculator</a> and <a href="/wire-gauge-calculator/">wire gauge calculator</a> handle precisely. Aluminum wire, where used, must be upsized versus copper because it carries less current per gauge.</p><p class="content-p">Never undersize wire to save money: the breaker protects the wire, so a 60 A breaker on 8 AWG wire is a fire risk because the wire can overheat before the breaker trips. When in doubt, size the wire for the breaker, not the charger, and have a licensed electrician verify the install and permit.</p>` },
    { type: 'section', id: 'how-to-use', icon: '✓', heading: 'How to Use the Home EV Charger Amp Calculator', html: `<ol><li><strong>Enter the charger power in kW.</strong> Use the charger's rated output — 7.4, 9.6, 11.5, or 19.2 kW are common. If you know the amperage instead, a 40 A charger at 240 V is 9.6 kW.</li><li><strong>Select the circuit voltage.</strong> Choose 240 V for a standard North American home, 208 V for a commercial three-phase building, or 120 V for a Level 1 outlet.</li></ol><p class="content-p">The calculator returns the charging current, the NEC-required breaker (already sized at 125% and rounded up), the continuous-load figure, and the miles of range added per hour. Use the breaker and continuous-load numbers to spec the circuit, and the range-per-hour figure to sanity-check whether the charger keeps up with your daily driving. To turn the charger power into a charge time for your specific battery, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a>; to see the running cost, the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a> and the <a href="/electricity-cost-calculator/">electricity cost calculator</a>.</p>` },
    { type: 'section', id: 'panel', icon: '▤', heading: 'Panel Capacity and Load Management', html: `<p class="content-p">Before adding a 40–60 A EV circuit, confirm your electrical panel can handle it. A new charger is often the largest single load in a home, and older panels can be close to their limit.</p><p class="content-p"><strong>Service size.</strong> Most modern homes have a 200 A service, which usually has room for a Level 2 charger. Older homes with 100 A service may need a load calculation (NEC 220) to confirm the charger fits alongside the HVAC, range, dryer, and water heater — or may need a service upgrade.</p><p class="content-p"><strong>Load management.</strong> If the panel is tight, a smart charger or an energy-management system can throttle or pause charging when other big loads run, letting you install a high-power charger without upgrading the service. Some chargers share a circuit with a dryer using a splitter that prevents both running at once.</p><p class="content-p"><strong>Continuous-load headroom.</strong> Remember the 125% rule applies to the panel calculation too. A 48 A charger counts as a 60 A continuous load in the service calculation, not 48 A. When adding the numbers up, use the continuous figure the calculator provides.</p><p class="content-p">A licensed electrician should perform the load calculation and pull the permit. The calculator gives you the circuit numbers to bring to that conversation so you arrive informed about breaker and wire needs.</p>` },
    { type: 'section', id: 'speed-table', icon: '⏱', heading: 'Charging Speed by Amperage', html: `<p class="content-p">Higher amperage means faster charging, but only up to what the car's onboard charger accepts. The table shows charging power and approximate range added per hour for common home circuit sizes at 240 V, using a typical 3.5 miles per kWh.</p><p class="content-p">Notice that a 48 A charger on a 60 A circuit is roughly the practical ceiling for most homes and covers even high-mileage drivers overnight. Many EVs cap their onboard AC charger at 32–48 A, so a bigger circuit only helps if the car can use it — check the vehicle's onboard charger rating before paying for an 80 A install.</p>`, table: { caption: 'Home charging speed by circuit size (240 V)', columns: ['Breaker', 'Max Charger Amps (80%)', 'Charging Power', 'Range Added/hr'], rows: [['20 A', '16 A', '3.8 kW', '~13 mi'], ['30 A', '24 A', '5.8 kW', '~20 mi'], ['40 A', '32 A', '7.7 kW', '~27 mi'], ['50 A', '40 A', '9.6 kW', '~34 mi'], ['60 A', '48 A', '11.5 kW', '~40 mi'], ['100 A', '80 A', '19.2 kW', '~67 mi']] } },
    { type: 'section', id: 'mistakes', icon: '!', heading: 'Common Mistakes When Sizing an EV Circuit', html: `<ul><li><strong>Skipping the 125% rule.</strong> Putting a 48 A charger on a 50 A breaker will nuisance-trip and violates code; it needs a 60 A circuit.</li><li><strong>Undersizing the wire.</strong> The breaker protects the wire — a 60 A breaker demands wire rated for 60 A (6 AWG copper), never less.</li><li><strong>Ignoring voltage drop on long runs.</strong> Runs over about 50 feet often need the next larger gauge; use the voltage drop calculator.</li><li><strong>Buying more charger than the car can use.</strong> Many EVs cap AC charging at 32–48 A; an 80 A charger then adds cost without speed.</li><li><strong>Forgetting the panel load calculation.</strong> A big continuous load may exceed an older service; verify capacity first.</li></ul><p class="content-p">Always have a licensed electrician confirm the design and permit the work. For the downstream questions of charge time and cost, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a> and <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a>.</p>` },
  ],
  faq: [
    { q: 'How many amps does a home EV charger need?', a: 'It depends on the charger power. An 11.5 kW charger at 240 V draws about 48 A and needs a 60 A breaker (125% rule). A 7.4 kW charger draws about 31 A and needs a 40 A breaker. A 9.6 kW charger draws 40 A and needs a 50 A breaker. Always size the breaker at 125% of the charging current because EV charging is a continuous load.' },
    { q: 'What size breaker do I need for an EV charger?', a: 'Multiply the charging amps by 1.25 and round up to the next standard size. A 40 A charger needs a 50 A breaker; a 48 A charger needs a 60 A breaker; a 32 A charger needs a 40 A breaker. This 125% factor is required by NEC 625.41 for continuous loads, and equivalently means the charger draws at most 80% of the breaker rating.' },
    { q: 'What wire gauge do I need for a home EV charger?', a: 'Match the wire to the breaker using 75°C copper ampacity: 12 AWG for a 20 A circuit, 8 AWG for 40 A, 6 AWG for 50–60 A, and 4 AWG for 70 A or long 60 A runs. The breaker protects the wire, so never use wire rated below the breaker. Long runs need an upsize for voltage drop — check the voltage drop calculator.' },
    { q: 'How many miles per hour does a Level 2 charger add?', a: 'Roughly the charger power in kW times about 3.5 miles per kWh. A 7.7 kW charger adds about 27 miles per hour; an 11.5 kW charger about 40 miles per hour; a 19.2 kW charger about 67 miles per hour. Actual figures vary with the car\'s efficiency, temperature, and whether the onboard charger can accept the full power.' },
    { q: 'Can I install an EV charger on a 100 A panel?', a: 'Often yes, but it requires an NEC load calculation to confirm the charger fits alongside your other large loads. If the panel is tight, a smart charger with load management can throttle charging when the HVAC or dryer runs, avoiding a service upgrade. A licensed electrician should perform the calculation and pull the permit.' },
    { q: 'Why is EV charging a continuous load?', a: 'The NEC defines a continuous load as one expected to run at maximum current for three hours or more. EV charging routinely runs for hours at steady full current, so it qualifies. Continuous loads require the circuit and breaker to be rated at 125% of the load, which is why a 48 A charger needs a 60 A circuit rather than a 50 A one.' },
    { q: 'Should I get a 48 A or 40 A charger?', a: 'A 40 A charger (9.6 kW) on a 50 A circuit is cheaper to install and adds about 34 miles per hour, plenty for most drivers. A 48 A charger (11.5 kW) on a 60 A circuit adds about 40 miles per hour but needs heavier wire and a bigger breaker. Choose based on your daily mileage and whether your car\'s onboard charger can even accept 48 A — many cap at 32–40 A.' },
  ],
  related: [
    { href: '/ev-charging-time-calculator/', badge: 'h', title: 'EV Charging Time Calculator', desc: 'How long a charge session takes' },
    { href: '/ev-charging-cost-calculator/', badge: '$', title: 'EV Charging Cost Calculator', desc: 'Cost to charge your EV' },
    { href: '/wire-gauge-calculator/', badge: 'AWG', title: 'Wire Gauge Calculator', desc: 'Size conductors for any load' },
    { href: '/voltage-drop-calculator/', badge: 'V', title: 'Voltage Drop Calculator', desc: 'Check drop on long runs' },
    { href: '/ev-range-calculator/', badge: 'mi', title: 'EV Range Calculator', desc: 'Miles from a full charge' },
    { href: '/electricity-cost-calculator/', badge: 'kWh', title: 'Electricity Cost Calculator', desc: 'Cost of energy per kWh' },
  ],
};

const evRange = {
  slug: 'ev-range-calculator',
  category: 'EV & Charging Calculators',
  kicker: 'EV range estimation',
  h1: 'EV Range Calculator',
  title: 'EV Range Calculator — Electric Car Range from Battery Size | Ampstowatt',
  metaDesc: 'Calculate electric car range from battery size and efficiency. Enter kWh, miles per kWh, and usable percentage to estimate driving range in miles and km plus energy per 100 miles.',
  keywords: ['ev range calculator', 'electric car range', 'ev driving range calculator', 'electric vehicle range', 'ev range estimator', 'ev miles per kwh calculator'],
  formulaPill: 'Range (mi) = kWh × Efficiency × Usable%',
  lead: 'Estimate the <strong>driving range of an electric car</strong> from its battery size and efficiency. This EV range calculator multiplies usable battery capacity by miles per kWh to give a realistic range in miles and kilometers, plus the energy used per 100 miles for easy comparison.',
  reviewed: 'September 5, 2026',
  featureList: ['Range in miles and kilometers', 'Efficiency-based (miles per kWh)', 'Usable-capacity aware', 'Energy per 100 miles output'],
  methodology: 'The calculator multiplies battery capacity by driving efficiency (miles per kWh) and by the usable fraction of the pack to estimate range. Efficiency values reflect real driving: efficient sedans achieve 4+ mi/kWh, while trucks and SUVs at highway speed may see 2–2.5 mi/kWh. Usable percentage accounts for the buffer automakers reserve at the top and bottom of the pack.',
  calc: {
    id: 'ev-range',
    title: 'EV Range Calculator',
    subtitle: 'Estimate electric car driving range from battery size and efficiency.',
    primaryLabel: 'Estimated Range',
    primaryUnit: 'miles',
    formulaText: 'Range = Battery kWh × Efficiency × Usable%',
    note: 'Usable energy times miles per kWh.',
    secondary: [
      { label: 'Range', unit: 'km' },
      { label: 'Usable Energy', unit: 'kWh' },
      { label: 'Energy per 100 mi', unit: 'kWh' },
    ],
    inputs: [
      { id: 'battery', label: 'Battery Capacity', unit: 'kWh', type: 'number', value: 60, min: 0 },
      { id: 'efficiency', label: 'Driving Efficiency', unit: 'mi/kWh', type: 'number', value: 3.5, min: 0, step: 0.1 },
      { id: 'usable', label: 'Usable Capacity', unit: '%', type: 'number', value: 90, min: 1, max: 100 },
    ],
    compute: function compute(v) {
      var usableKWh = v.battery * (v.usable / 100);
      var rangeMi = usableKWh * v.efficiency;
      var rangeKm = rangeMi * 1.60934;
      var per100 = v.efficiency > 0 ? 100 / v.efficiency : 0;
      return {
        primary: { label: 'Estimated Range', value: rangeMi, unit: 'miles', precision: 0 },
        secondary: [
          { label: 'Range', value: rangeKm, unit: 'km', precision: 0 },
          { label: 'Usable Energy', value: usableKWh, unit: 'kWh', precision: 1 },
          { label: 'Energy per 100 mi', value: per100, unit: 'kWh', precision: 1 },
        ],
        formula: 'Range = ' + v.battery + ' kWh × ' + v.efficiency + ' mi/kWh × ' + v.usable + '%',
        note: usableKWh.toFixed(1) + ' usable kWh at ' + v.efficiency + ' mi/kWh.',
      };
    },
    tests: [
      { name: '60kWh 3.5mi/kWh 90%', in: { battery: 60, efficiency: 3.5, usable: 90 }, expect: 189, tol: 0.01 },
      { name: '100kWh 3.0mi/kWh 95%', in: { battery: 100, efficiency: 3.0, usable: 95 }, expect: 285, tol: 0.01 },
    ],
  },
  content: [
    { type: 'section', id: 'quick-answer', icon: '⚡', heading: 'How Far Can an Electric Car Go? Quick Answer', html: `<p class="content-p"><strong>To estimate EV range, multiply usable battery capacity by driving efficiency in miles per kWh.</strong> A 60 kWh battery with 90% usable capacity holds 54 usable kWh. At a typical 3.5 miles per kWh, that gives about <strong>189 miles</strong> of range (304 km). The calculator above returns range in both miles and kilometers, plus the usable energy and the energy used per 100 miles.</p><p class="content-p">Real range depends far more on <strong>efficiency</strong> than on battery size alone. The same 60 kWh pack delivers 240 miles in an aerodynamic sedan at 4.0 mi/kWh but only 150 miles in a boxy truck at 2.5 mi/kWh. Speed, temperature, terrain, and climate control all move efficiency, so entering a realistic mi/kWh for your driving matters more than the headline EPA number. To plan the charging behind that range, use the <a href="/ev-charging-time-calculator/">EV charging time calculator</a>.</p>` },
    { type: 'section', id: 'formula', icon: 'f(x)', heading: 'The EV Range Formula Explained', html: `<p class="content-p">The equation used by this calculator is:</p><div class="tool-guide-formula">Range (miles) = Battery kWh × Usable% × Efficiency (miles per kWh)</div><p class="content-p">Each term drives the result:</p><ul><li><strong>Battery kWh</strong> — the pack's total capacity. Bigger packs carry more energy and therefore more range, all else equal.</li><li><strong>Usable percentage</strong> — automakers reserve a buffer at the top and bottom of the pack to protect longevity, so a "64 kWh gross" battery might offer about 58 kWh usable. Use 90% as a reasonable default when the usable figure is unknown.</li><li><strong>Efficiency (miles per kWh)</strong> — how far the car travels on one kilowatt-hour. This is the biggest lever: efficient EVs exceed 4 mi/kWh, while heavy trucks at highway speed can drop to 2 mi/kWh.</li></ul><p class="content-p">Multiplying usable energy by miles per kWh gives range directly. The inverse of efficiency, energy per 100 miles, is a useful comparison metric the calculator also reports — lower is better, like a car's fuel consumption. To translate that energy into charging cost, pair this with the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a>.</p>`, table: { caption: 'Typical EV efficiency by vehicle type', columns: ['Vehicle Type', 'Efficiency (mi/kWh)', 'Energy per 100 mi', 'Example Range on 60 kWh*'], rows: [['Efficient compact EV', '4.0–4.5', '22–25 kWh', '216–243 mi'], ['Midsize sedan', '3.3–3.8', '26–30 kWh', '178–205 mi'], ['Crossover / small SUV', '3.0–3.4', '29–33 kWh', '162–184 mi'], ['Large SUV', '2.5–2.9', '34–40 kWh', '135–157 mi'], ['Electric truck', '2.0–2.5', '40–50 kWh', '108–135 mi']] } },
    { type: 'section', id: 'examples', icon: '#', heading: 'Worked Examples: Estimating Real EV Range', html: `<p class="content-p">These examples show how efficiency and usable capacity reshape range for different vehicles.</p><p class="content-p"><strong>Example 1 — 60 kWh compact EV at 3.5 mi/kWh, 90% usable:</strong> Usable energy = 60 × 0.90 = 54 kWh. Range = 54 × 3.5 = <strong>189 miles</strong> (304 km). Energy per 100 miles = 100 ÷ 3.5 = 28.6 kWh. This is a typical everyday commuter figure.</p><p class="content-p"><strong>Example 2 — 100 kWh luxury SUV at 3.0 mi/kWh, 95% usable:</strong> Usable = 100 × 0.95 = 95 kWh. Range = 95 × 3.0 = <strong>285 miles</strong> (459 km). The bigger battery buys long range despite lower efficiency, at the cost of weight and price.</p><p class="content-p"><strong>Example 3 — 77 kWh sedan on the highway at 3.0 mi/kWh vs city at 4.2 mi/kWh:</strong> At 90% usable (69.3 kWh), highway range = 69.3 × 3.0 = <strong>208 miles</strong>, but efficient city driving = 69.3 × 4.2 = <strong>291 miles</strong>. The same car swings 80+ miles based on how and where you drive.</p><p class="content-p"><strong>Example 4 — 131 kWh electric truck at 2.2 mi/kWh, 92% usable:</strong> Usable = 131 × 0.92 = 120.5 kWh. Range = 120.5 × 2.2 = <strong>265 miles</strong>. Towing or hauling can cut truck efficiency to 1.5 mi/kWh or below, roughly halving range — a key planning factor for work use.</p>` },
    { type: 'section', id: 'efficiency-factors', icon: '⚙', heading: 'What Changes Your EV Efficiency (and Range)', html: `<p class="content-p">Miles per kWh is not a fixed number; it moves with conditions, and understanding the drivers lets you set a realistic value.</p><p class="content-p"><strong>Speed and aerodynamics.</strong> Aerodynamic drag rises with the square of speed, so highway cruising at 75 mph uses far more energy per mile than 55 mph. This is why EVs, unlike gas cars, often show <em>lower</em> range on the highway than in the city.</p><p class="content-p"><strong>Temperature.</strong> Cold weather is the biggest range killer. Battery chemistry slows in the cold, and cabin heating draws several kilowatts. Winter range can fall 20–40% versus mild weather. Heat pumps and preconditioning while plugged in soften the hit.</p><p class="content-p"><strong>Terrain and load.</strong> Climbing hills, carrying passengers, and towing all raise energy per mile. Regenerative braking recovers some energy on descents, which is why hilly routes net out better than they feel.</p><p class="content-p"><strong>Driving style and tires.</strong> Hard acceleration, underinflated tires, and roof racks all cut efficiency. Smooth driving and correct tire pressure can add 10–15% range for free. When estimating, pick a mi/kWh that matches your typical conditions rather than the best-case EPA rating — then use the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a> to see the cost per mile that efficiency implies.</p>` },
    { type: 'section', id: 'how-to-use', icon: '✓', heading: 'How to Use the EV Range Calculator', html: `<ol><li><strong>Enter battery capacity in kWh.</strong> Use the usable figure if you have it; otherwise the gross capacity with a usable percentage below handles the buffer.</li><li><strong>Enter driving efficiency in miles per kWh.</strong> Check your car's trip computer for a real average. Use 3.5 as a general default, 4.0+ for an efficient sedan, or 2.5 for a truck or highway driving.</li><li><strong>Set usable capacity.</strong> Use 90% as a default if you entered gross capacity, or 100% if you already entered the usable figure.</li></ol><p class="content-p">The result shows range in miles and kilometers, usable energy, and energy per 100 miles. Lower the efficiency to model winter or highway driving, or raise it for gentle city commuting, to see your realistic range envelope. Once you know the range you need, the <a href="/ev-charging-time-calculator/">EV charging time calculator</a> shows how long to refill it and the <a href="/home-ev-charger-amp-calculator/">home EV charger amp calculator</a> sizes the circuit to do so.</p>` },
    { type: 'section', id: 'epa-vs-real', icon: '◎', heading: 'EPA Range vs Real-World Range', html: `<p class="content-p">The range on the window sticker is a standardized test figure, and your real range will differ, sometimes a lot. Knowing why helps you set expectations and inputs.</p><p class="content-p"><strong>EPA and WLTP ratings.</strong> The US EPA and European WLTP cycles mix city and highway driving under controlled conditions. They are useful for comparing cars but assume moderate temperatures and speeds. WLTP figures tend to run optimistic versus EPA for the same car.</p><p class="content-p"><strong>Highway penalty.</strong> Because most rating cycles weight city driving, EVs often fall short of their rated range on a steady highway trip at 70–75 mph. Planning a road trip on 80–90% of the rated range is prudent.</p><p class="content-p"><strong>Winter and degradation.</strong> Cold weather and long-term battery degradation both trim usable range. After several years a pack may hold 90% of its original capacity; enter that in the usable field for an aged-battery estimate.</p><p class="content-p">This calculator lets you build these realities in: enter your observed mi/kWh and a usable percentage that reflects your battery's health and conditions, rather than trusting a single sticker number. The result is a range you can actually plan around, and pairing it with the <a href="/battery-runtime-calculator/">battery runtime calculator</a> extends the same energy thinking to other battery systems.</p>` },
    { type: 'section', id: 'range-table', icon: '⏱', heading: 'EV Range Reference Table by Battery and Efficiency', html: `<p class="content-p">The table shows estimated range (miles) for common battery sizes across a range of efficiencies, assuming 90% usable capacity. Use it as a fast sanity check against the live calculator.</p><p class="content-p">Notice how efficiency and battery size trade off: a 60 kWh pack in an efficient car can outrange a 75 kWh pack in an inefficient one. When shopping, compare cars on efficiency (mi/kWh) as well as battery size, because efficiency also determines charging cost per mile and how far each fast-charge stop takes you.</p>`, table: { caption: 'Estimated range in miles (90% usable capacity)', columns: ['Battery Size', '2.5 mi/kWh', '3.0 mi/kWh', '3.5 mi/kWh', '4.0 mi/kWh'], rows: [['40 kWh', '90 mi', '108 mi', '126 mi', '144 mi'], ['60 kWh', '135 mi', '162 mi', '189 mi', '216 mi'], ['77 kWh', '173 mi', '208 mi', '243 mi', '277 mi'], ['100 kWh', '225 mi', '270 mi', '315 mi', '360 mi'], ['131 kWh', '295 mi', '354 mi', '413 mi', '472 mi']] } },
    { type: 'section', id: 'maximize', icon: '↑', heading: 'How to Maximize Your EV Range', html: `<p class="content-p">Because range is efficiency multiplied by usable energy, anything that raises miles per kWh directly extends how far you go on a charge — often by 10–20% with no hardware changes.</p><p class="content-p"><strong>Moderate your speed.</strong> Aerodynamic drag climbs with the square of velocity, so easing off from 75 to 65 mph on a long highway leg can add 10–15% range. On road trips this often means one fewer charging stop.</p><p class="content-p"><strong>Use regenerative braking.</strong> Lifting off early and letting regen slow the car recovers energy that friction brakes would waste as heat. One-pedal driving in stop-and-go traffic is where EVs shine and why city efficiency usually beats highway.</p><p class="content-p"><strong>Precondition while plugged in.</strong> Heating or cooling the cabin and warming the battery from grid power, before you unplug, means that energy does not come out of the pack. In winter this alone can preserve a meaningful chunk of range.</p><p class="content-p"><strong>Mind tires and cargo.</strong> Underinflated tires, roof racks, and unnecessary weight all cut efficiency. Correct pressure and removing an unused roof box are free range. Eco driving modes cap acceleration and climate draw to stretch the last miles when you are cutting it close.</p><p class="content-p">Enter a higher mi/kWh above to see the payoff of efficient driving, or a lower one to model a worst-case winter highway run. The gap between the two is your practical planning envelope, and pairing it with the <a href="/ev-charging-time-calculator/">EV charging time calculator</a> tells you how long each refill takes.</p><p class="content-p">For road trips, plan legs around 70–80% of your realistic range rather than the maximum, leaving a safety buffer for detours, headwinds, and the fact that fast charging is slowest at very low state of charge. Arriving at a charger with 10–20% left keeps the session in the fast part of the charge curve and avoids range anxiety. Enter your highway mi/kWh, not your city average, when sizing trip legs — the difference of a single mile per kWh can move a leg by 50 miles or more.</p>` },
    { type: 'section', id: 'mistakes', icon: '!', heading: 'Common Mistakes in EV Range Estimates', html: `<ul><li><strong>Using gross capacity as usable.</strong> Automakers reserve a buffer; apply a usable percentage or the range will read high.</li><li><strong>Trusting a single EPA number.</strong> Highway speed, cold, and terrain can cut real range 20–40% below the rating.</li><li><strong>Assuming highway range beats city range.</strong> For EVs it is usually the reverse, because drag dominates at speed.</li><li><strong>Ignoring degradation.</strong> An older pack holds less; lower the usable percentage for an aged battery.</li><li><strong>Forgetting climate and cargo loads.</strong> Heating, towing, and roof racks all cut miles per kWh noticeably.</li></ul><p class="content-p">For the full ownership picture, combine range with the <a href="/ev-charging-time-calculator/">EV charging time calculator</a>, the <a href="/ev-charging-cost-calculator/">EV charging cost calculator</a>, and the <a href="/electricity-cost-calculator/">electricity cost calculator</a>.</p>` },
  ],
  faq: [
    { q: 'How do I calculate the range of an electric car?', a: 'Multiply the usable battery capacity by the driving efficiency in miles per kWh. A 60 kWh battery at 90% usable (54 kWh) and 3.5 mi/kWh gives about 189 miles. Efficiency matters most: the same battery delivers 216 miles at 4.0 mi/kWh or 135 miles at 2.5 mi/kWh, so use a realistic figure for your driving.' },
    { q: 'What is a good miles-per-kWh for an EV?', a: 'Efficient compact EVs achieve 4.0–4.5 mi/kWh, midsize sedans 3.3–3.8, crossovers 3.0–3.4, large SUVs 2.5–2.9, and electric trucks 2.0–2.5. City driving and mild weather push efficiency up; highway speed, cold, hills, and towing pull it down. Check your car\'s trip computer for your real average.' },
    { q: 'Why is my real range lower than the EPA rating?', a: 'EPA figures assume moderate temperatures and mixed driving. Real range drops on the highway (aerodynamic drag rises with speed), in cold weather (slower chemistry plus cabin heating can cut 20–40%), on hilly terrain, and with heavy loads or towing. Plan trips on about 80–90% of the rated range to stay safe.' },
    { q: 'How much does cold weather reduce EV range?', a: 'Typically 20–40% in freezing conditions. The battery delivers less energy when cold and cabin heating can draw several kilowatts continuously. Preconditioning the car while plugged in, using seat heaters instead of cabin heat, and a heat pump all reduce the loss. Enter a lower mi/kWh to model winter range.' },
    { q: 'Does a bigger battery always mean more range?', a: 'More capacity helps, but efficiency matters just as much. A 60 kWh efficient sedan at 4.0 mi/kWh (216 miles) can outrange a 75 kWh inefficient SUV at 2.6 mi/kWh (about 176 miles at 90% usable). Compare cars on both battery size and miles per kWh, since efficiency also sets your charging cost per mile.' },
    { q: 'What is energy per 100 miles and why does it matter?', a: 'It is the inverse of efficiency — how many kWh the car uses to travel 100 miles. At 3.5 mi/kWh that is about 28.6 kWh per 100 miles; at 4.0 mi/kWh it is 25 kWh. Lower is better, like fuel consumption. It makes comparing EVs and estimating charging cost straightforward: multiply by your electricity rate for cost per 100 miles.' },
    { q: 'How does battery degradation affect range?', a: 'Batteries slowly lose capacity, often retaining around 90% after several years and many cycles. That directly reduces usable energy and range. To model an aged pack, lower the usable-capacity input — for example set it to 85% for an older battery — so the range estimate reflects the real, current capacity rather than the original figure.' },
  ],
  related: [
    { href: '/ev-charging-time-calculator/', badge: 'h', title: 'EV Charging Time Calculator', desc: 'How long to charge for this range' },
    { href: '/ev-charging-cost-calculator/', badge: '$', title: 'EV Charging Cost Calculator', desc: 'Cost per charge and per mile' },
    { href: '/home-ev-charger-amp-calculator/', badge: 'A', title: 'Home EV Charger Amp Calculator', desc: 'Size the charging circuit' },
    { href: '/battery-charge-time-calculator/', badge: 'Ah', title: 'Battery Charge Time Calculator', desc: 'Charge time for 12 V batteries' },
    { href: '/battery-runtime-calculator/', badge: 'h', title: 'Battery Runtime Calculator', desc: 'How long a battery lasts' },
    { href: '/electricity-cost-calculator/', badge: 'kWh', title: 'Electricity Cost Calculator', desc: 'Cost of energy per kWh' },
  ],
};

module.exports = [evChargingTime, evChargingCost, batteryChargeTime, homeEvChargerAmp, evRange];
